### ISSUE TITLE
shouldn't a failed expectation in ghttp return a non-200 status code?

### ISSUE THREAD

**Issue by tve** [onsi/gomega#100]
I'm writing high-level tests for a fairly complicated library that makes several http requests and when an assertion in a ghtttp server fails (for example in `ghttp.VerifyRequest`) then the caller gets a 200 OK response code ('cause nothing writes to the ResponseWriter and the default status code is 200 OK). The result is that the client code keeps on truckin' and makes more requests. The test eventually prints the failing expectation, but it's impossible to figure out which request failed. It seems to me that ghttpServeHTTP should rescue the panic (I believe that's what Ω does), write a 5XX status code, and re-raise.
(It would also be awesome if one could turn on some logging in ghttp so it produces a 1-liner for each request and response.)

**Comment by onsi** [comment]
These are good ideas.  I'll try to work on it soon though if you're up for a PR it would be much appreciated :)

**Comment by onsi** [comment]
Actually, I think I might have some time to work on this right now.

**Comment by onsi** [comment]
Take a look at the latest two commits:

- failed assertions and panics now cause `ghttp` servers to return 500
- a panic in a registered handler now actually registers as a failure (this was missing behavior!!)
- if you set the `Writer` property on a `ghttp` server it will log a line for every incoming request.

It's hard to meaningfully log a line for the response.  I could wrap the `http.ResponseWriter` object to intercept what the registered handlers are doing with it but this is notoriously difficult as Go breaks its own abstractions by allowing you to sniff for "hidden" interfaces (e.g. `Hijacker`, `Flusher`) and I'd have to bend over backwards to make sure I didn't break handlers that were doing this.  tl;dr - the best I can *safely* do is log "GHTTP Responded" which isn't very useful.
