### ISSUE TITLE
Comparing pointers?

### ISSUE THREAD

**Issue by elliotchance** [onsi/gomega#104]
I want to test if two objects have the same pointer:

```go
func GetRoot() *BluePrintObject {
    return new(BluePrintObject)
}
```

```go
var _ = Describe("Blueprint", func() {
    Context("The root node", func () {
        var rootNode = GetRoot()
        It("should be a singleton", func () {
            var anotherRootNode = GetRoot()
            Ω(rootNode).Should(Equal(anotherRootNode))
        })
    })
})
```

This passes, however I want it to fail since they are different memory locations. How about a new matcher?

```go
Ω(rootNode).Should(BeTheSameObjectAs(anotherRootNode))
```

**Comment by elliotchance** [comment]
For the time being I can use:

```go
Ω(rootNode == anotherRootNode).Should(BeTrue())
``

**Comment by onsi** [comment]
hey @elliotchance I'd be happy to pull in a PR if you're up for putting it together.  Should be fairly straightforward to copy and paste your way to victory though you might want to make sure to handle `nil` appropriately (might just work, always a tricky edge case).

A code PR + docs PR to the gh-pages branch would be great.

As for the matcher name, another option could be `BeIdenticalTo()` or `StrictlyEqual()`.

**Comment by tjarratt** [comment]
:+1: would love to have a `BeIdenticalTo()` matcher in Gomega. This is probably one of my favorite matchers from Cedar that I've been missing when writing Go.

@elliotchance -- were you working on a PR? Would you be terribly upset if I worked on this?

**Comment by elliotchance** [comment]
@tjarratt upset from someone helping? Never! :) Go for it.

Sorry @onsi, I forgot entirely about this request.

**Comment by onsi** [comment]
Thanks  @tjarratt

**Comment by tjarratt** [comment]
Thank you @onsi and @elliotchance!
