### ISSUE TITLE
Testing that an error condition occurred

### ISSUE THREAD

**Issue by davisford** [onsi/gomega#106]
I understand this shortcut for testing that the return value was `<something>, <nil>`

```go		
Ω(cm.DoThing(input)).Should(Equal("some value")) 
```

Which asserts that the `error` is `nil`, and the return value is non-nil and equal to whatever you pass it, but how to test the opposite scenario?  The one where you want to assert that the error is *not* `nil` and the return value is nil.

I'm guessing there is no one-liner short-cut for that, and would have to be done as:
```go
resp, err := DoThing(input)
Expect(resp).To(BeNil())
Expect(err).ToNot(BeNil())
```

**Comment by onsi** [comment]
Yep.  That's exactly right.  The "error should be nil" assertion applies across the board and is handled by Expect.  The matcher never sees more than the first return value.

**Comment by davisford** [comment]
Ok, thanks @onsi

**Comment by decibel** [comment]
This is a really common pattern: a function that returns an arbitrary number of values, and finally an error, and if there's an error all return values will be their zero value (except obviously the final error value).

It would be really nice if there was some way to do a single call that verifies that all return values are their zero value, and the final error value matches what you want.

I guess the best way to handle that would be a different form of Expect()?
