### ISSUE TITLE
Add ghttp.Verify body method

### ISSUE THREAD

**Issue by robdimsdale** [onsi/gomega#110]
In `ghttp/handlers.go` I would like to see a `VerifyBody([]byte) http.HandlerFunc` method.

This would assert that the received request contains a body that matches, byte for byte, the expected body.

Currently there is `VerifyJSON` and `VerifyJSONRepresenting` for a body that conforms to JSON - I'm looking for the same idea but for an arbitrary body.

Thoughts?

**Comment by onsi** [comment]
SGTM - PR welcome!

**Comment by robdimsdale** [comment]
PR was merged - closing this issue.
