### ISSUE TITLE
Missing protobuf dependency

### ISSUE THREAD

**Issue by evanshort73** [onsi/gomega#114]
`go get github.com/onsi/gomega` does not cause `github.com/golang/protobuf` to be downloaded. This may be because the import is in a file called `ghttp/protobuf/simple_message.pb.go` which Go might not recognize as having a `.go` file extension.

**Comment by onsi** [comment]
Did you try to `go get -t github.com/onsi/gomega`?

**Comment by evanshort73** [comment]
I just tried that. I deleted `github.com/golang/protobuf` and `github.com/onsi/gomega` from my gopath and ran `go get -t github.com/onsi/gomega`. The gomega folder was restored but the protobuf folder was still missing.

**Comment by onsi** [comment]
hmm.. so looking into this, `github.com/golang/protobuf` is only imported by `github.com/onsi/gomega/ghttp`.

I find that `go get github.com/onsi/gomega/...` does the trick.

the introduction of `protobuf` is fairly recent.

I confess I find this behavior in Go confusing and it's not something I've run into before.  It looks like `go get foo` only fetches the dependencies associated with `foo` and not any packages hosted within `foo`'s subdirectories that the top-level `foo` does not import...

**Comment by james-lawrence** [comment]
OS dependent issue? evan what os do you work on?

**Comment by onsi** [comment]
Closing this out as a dupe of #123
