### ISSUE TITLE
While import gomega got following error

### ISSUE THREAD

**Issue by gurbachan-singh-jabong** [onsi/gomega#127]
src/github.com/onsi/gomega/matchers.go:344: undefined: matchers.BeADirectoryMatcher
src/github.com/onsi/gomega/matchers.go:353: undefined: matchers.AndMatcher
src/github.com/onsi/gomega/matchers.go:368: undefined: matchers.OrMatcher
src/github.com/onsi/gomega/matchers.go:382: undefined: matchers.NotMatcher
src/github.com/onsi/gomega/matchers.go:392: undefined: matchers.NewWithTransformMatcher

**Comment by robdimsdale** [comment]
Hi @gurbachan-singh-jabong 

There's not quite enough information here for me to help figure out what's going on. Can you explain what you were trying to do, and the steps you took that led to the above error?

Thanks,
Rob

**Comment by gurbachan-singh-jabong** [comment]
Go build is broken due to 

src/github.com/onsi/gomega/matchers.go:344: undefined: matchers.BeADirectoryMatcher
src/github.com/onsi/gomega/matchers.go:353: undefined: matchers.AndMatcher
src/github.com/onsi/gomega/matchers.go:368: undefined: matchers.OrMatcher
src/github.com/onsi/gomega/matchers.go:382: undefined: matchers.NotMatcher
src/github.com/onsi/gomega/matchers.go:392: undefined: matchers.NewWithTransformMatcher

**Comment by robdimsdale** [comment]
There is no such file `src/github.com/onsi/gomega/matchers.go` - is your copy of gomega outdated maybe?

If you `go get -u github.com/onsi/gomega` what happens?

**Comment by robdimsdale** [comment]
wait sorry ignore that last comment I was looking in the wrong place. Let me take another look

**Comment by gurbachan-singh-jabong** [comment]
Thansk for your showing effort

**Comment by robdimsdale** [comment]
I can't reproduce this: when I run `go build ./...` from the gomega directory with the latest SHA it works fine.

Can you post the steps you're running to encounter this error?

**Comment by robdimsdale** [comment]
@gurbachan-singh-jabong I'm going to close this issue as it's been a couple of weeks without response. Please feel free to open another issue if you continue to encounter problems.
