### ISSUE TITLE
MatchJSON failure messages are opaque and (at times) misleading

### ISSUE THREAD

**Issue by tjarratt** [onsi/gomega#131]
I was using the `MatchJSON` matcher recently and had a heck of a time figuring out what some of the error messages bubbled up from the `encoding/json` package actually meant.

In particular, when neither the `actual`, nor the `expected` is valid as JSON, it's very hard to tell what to change next -- most of the time I had to resort to printing out both and trying to parse it as JSON myself.

It would be really nice if the error messages could be improved to indicate which of the two cannot be parsed as JSON which this occurs.

**Comment by robdimsdale** [comment]
Agreed. I think a PR to this section would be well received. A simple change might be to add `json.Marshal` on both the expected and the actualy to https://github.com/onsi/gomega/blob/master/matchers/match_json_matcher.go#L48 

A much more ambitious solution would be to implement a more semantically-aware matcher that wouldn't just dump the string contents, but actually provide a meaningful object-level diff.

**Comment by tjarratt** [comment]
Agreed 100%

I was thinking of implementing the small PR and then tackling the larger
issue of improving how the matcher compares the json structures later.

If someone else wants to contribute a PR for this, I wouldn't be at all
upset. This seemed like a nice feature for a new contributor (such as
myself).

On Friday, February 19, 2016, Rob Dimsdale <notifications@github.com> wrote:

> Agreed. I think a PR to this section would be well received. A simple
> change might be to add json.Marshal on both the expected and the actualy
> to
> https://github.com/onsi/gomega/blob/master/matchers/match_json_matcher.go#L48
>
> A much more ambitious solution would be to implement a more
> semantically-aware matcher that wouldn't just dump the string contents, but
> actually provide a meaningful object-level diff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onsi/gomega/issues/131#issuecomment-186497475>.
>


-- 
Magnetized From My Etch-A-Sketch

**Comment by robdimsdale** [comment]
A PR would be great. Do you feel like you have enough guidance to tackle this, or can I help further?

**Comment by tjarratt** [comment]
I feel comfortable tackling this.

Thanks for the very kind words and support, Rob.

On Friday, February 19, 2016, Rob Dimsdale <notifications@github.com> wrote:

> A PR would be great. Do you feel like you have enough guidance to tackle
> this, or can I help further?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onsi/gomega/issues/131#issuecomment-186499941>.
>


-- 
Magnetized From My Etch-A-Sketch

**Comment by onsi** [comment]
Woot!  Thanks Tim!

**Comment by robdimsdale** [comment]
Closed via #136
