### ISSUE TITLE
Docs pages have broken links and headers

### ISSUE THREAD

**Issue by rosenhouse** [onsi/gomega#137]
The headers seem to show up with just hash marks in front of them:

![screen shot 2016-03-05 at 5 59 44 pm](https://cloud.githubusercontent.com/assets/4128521/13551831/208d9e74-e2fc-11e5-9ce4-03d33c881017.png)

And the links on the navigation side-bar are broken for those headers.  For example, clicking on "Making Assertions" updates my URL bar to `http://onsi.github.io/gomega/#making-assertions` but does not actually move my browser to that section of the page.

The Ginkgo docs have the same problems.  For example the link to `http://onsi.github.io/ginkgo/#structuring-your-specs` doesn't work.

**Comment by robdimsdale** [comment]
@rosenhouse I think this is related to the update to markdown syntax on github pages. I saw a similar issue on ginkgo too:

https://github.com/onsi/ginkgo/issues/220

I'd love to see this fixed, plus I think syntax highlighting is now supported. A PR would be great if you're willing?

**Comment by robdimsdale** [comment]
@rosenhouse this should be fixed via https://github.com/onsi/gomega/pull/138 - closing this issue now.
