### ISSUE TITLE
Receive() not working

### ISSUE THREAD

**Issue by santacruz123** [onsi/gomega#143]
> 		FIt("Subscribing", func() {
			wss := newws.New()
			err := wss.Connect()
			Expect(err).Should(Succeed())
			ch := wss.TickerCh()
			wss.SubTicker("BTCUSD")
			log.Println("Got from channel", <-ch) // Works
			Eventually(ch).Should(Receive())      // Fails here
		})

> SS2016/03/30 12:38:56 Connected to WS
2016/03/30 12:38:56 Writing to WS {"event":"subscribe","channel":"ticker","pair":"BTCUSD"}
2016/03/30 12:38:56 Starting WS reader
2016/03/30 12:38:56 Got from channel {413.72 413.75}

>     Timed out after 10.003s.
    Expected
        <chan newws.Ticker | len:0, cap:0>: 0xc820324c60
    to receive something.

**Comment by robdimsdale** [comment]
@santacruz123 what happens when you take the log line out, specifically the `<-`?

It could be that because you're waiting on the channel in the log line, you're preventing the `Eventually` from receiving the same value (because you've already read the value from the channel).

**Comment by santacruz123** [comment]
Duplicate - https://github.com/onsi/gomega/issues/82
