### ISSUE TITLE
Always escape a slice of bytes

### ISSUE THREAD

**Issue by Julio-Guerra** [onsi/gomega#147]
The type `[]byte` should be seen as memory and is mostly used for buffers and thus contain non-printable characters most of the time. Some of these non-printable characters can even be interpreted by the terminal, leading to bad side-effects (emacs' compilation buffer segfaulting in my case...).

I extracted the underlying formatting function gomage uses for `[]byte` to show you an example of what happens: https://play.golang.org/p/ycVWoncyYy

Related: https://blog.golang.org/strings

**Comment by robdimsdale** [comment]
@Julio-Guerra you raise some good points. In the interests of keeping the conversation in one place I'll close this issue and we can continue discussion on the PR at #148
