### ISSUE TITLE
`formatString()` vs `IndentString()`

### ISSUE THREAD

**Issue by Julio-Guerra** [onsi/gomega#149]
While fixing #147, I noticed the following about `formatString()`:
1. [this weird change of formatting behavior when `indentation == 1`](https://github.com/onsi/gomega/blob/master/format/format.go#L170) which uses indented `%s` with newlines, but an escaped string `%q` otherwise.
2. The indentation code of `formatString()` seems to be the same as [`IndentString()`](https://github.com/onsi/gomega/blob/master/format/format.go#L69)

**Comment by williammartin** [comment]
Yikes, sorry this never got looked at. Looks like those links no longer point to the correct place. Do you remember what this was about @Julio-Guerra?

Not sure this existed last year but now when looking at code in GitHub if you press `y`, you will get a URL including the commit sha for permanent links :)
