### ISSUE TITLE
cannot vendor gomega using govendor tool

### ISSUE THREAD

**Issue by christo4ferris** [onsi/gomega#156]
I was adding some ginkgo and gomega tests to the Hyperledger project, and oddly, I get an error when I run the tests after adding ginkgo and gomega to the vendor packages installed with the project. Removing and simply having ginkgo and gomega installed on my machine, everything builds just fine. 

Here's the error

vagrant@hyperledger-devenv:v0.0.9-b68df74:/opt/gopath/src/github.com/hyperledger/fabric$ make unit-test 
Obtaining list of tests to run..DONE!
Starting peer..DONE!
Running tests...
# github.com/hyperledger/fabric/core/ledger/test
package github.com/hyperledger/fabric/core/ledger/test_test
	imports github.com/onsi/gomega
	imports github.com/onsi/gomega/internal/assertion: use of internal package not allowed
FAIL	github.com/hyperledger/fabric/core/ledger/test [setup failed]

vagrant@hyperledger-devenv:v0.0.9-b68df74:/opt/gopath/src/github.com/hyperledger/fabric$ go version
go version go1.6 linux/amd64

I was also able to reproduce in the small, using the ginkgo books sample:

1. create project in your $GOPATH; cd $GOPATH/src/<yourproject>
2. add the books_test.go sample
3. mkdir -p vendor
4. govendor add github.com/onsi/gomega
    govendor add github.com/onsi/ginkgo/ginkgo
5. ginkgo -v

Failed to compile books:

package github.com/christo4ferris/books/vendor/github.com/onsi/gomega
	imports github.com/onsi/gomega/internal/assertion: use of internal package not allowed
package github.com/christo4ferris/books/vendor/github.com/onsi/gomega
	imports github.com/onsi/gomega/internal/asyncassertion: use of internal package not allowed
package github.com/christo4ferris/books/vendor/github.com/onsi/gomega
	imports github.com/onsi/gomega/internal/testingtsupport: use of internal package not allowed

Ginkgo ran 1 suite in 723.736771ms
Test Suite Failed

**Comment by tinygrasshopper** [comment]
I faced this issue with `govendor`, in the past. When you use `govendor add` it does not copy sub-packages named `internal` to the vendor directory. Which in turn leads the packages from the vendor directory referring to internal packages in the GOPATH, causing the `use of internal package not allowed` error. If you start using `govendor fetch` to fetch your dependencies you wont have that issue.

**Comment by christo4ferris** [comment]
@tinygrasshopper thanks! very helpful

**Comment by tinygrasshopper** [comment]
@christo4ferris no worries. this doesn't look like a issue on gomega are you ok to close it?

**Comment by AlbanSeurat** [comment]
Would it be possible to re-open this issue as it also happens with with gopk.in and the ticket here : https://github.com/golang/oauth2/issues/178 ask to move internal folder to lib folder

**Comment by sclevine** [comment]
Hi @AlbanSeurat,

Are you trying to import gomega with a gopkg.in path? Gomega does not support this.

If you're using govendor, could you try following the suggestions mentioned in the golang/oauth2 issue you linked? I don't think `/internal` should be moved to a different path.
