### ISSUE TITLE
Usage of `yaml.v2` library license

### ISSUE THREAD

**Issue by momchil-sap** [onsi/gomega#158]
Hi,

The following commit has introduced the `yaml.v2` library to this project: https://github.com/onsi/gomega/commit/c73e51675ad2455a4515b6213eb7145eaade4824

This library has the `GNU Lesser General Public License v3` license which is not in alignment with the `MIT` license that has been used so far.

* This has not been documented in the `README.md`, unlike the `MIT` license.
* This makes the library less attractive for commercial usage.

Regards,
Momchil

**Comment by robdimsdale** [comment]
@momchil-sap thanks for pointing this out. We have yet to find a yaml library that works as well as https://github.com/go-yaml/yaml/tree/v2 so we will likely stick with this library for the foreseeable future. If you are aware of such a library with more favorable licensing terms, please let us know! We would love to evaluate it.

We don't actually vendor in the code for the `yaml.v2` library - we introduce a dependency on it. If you don't use the `yaml` matcher you don't need the dependency. If you feel like that should be explicitly called out in the README please feel free to open a PR.

Thanks,
Rob

**Comment by momchil-sap** [comment]
@robdimsdale , using the [godep](https://github.com/tools/godep) tool, the library is pulled in as well. Probably has to do with the fact that one transitively depends on the `matchers` package as a whole. I presume the same is valid when the whole `GOPATH` is versioned in a repository (e.g. [loggregator](https://github.com/cloudfoundry/loggregator))

Now, I am not a legal expert, but I presume that shipping a library with you code (in those cases when you want to ship tests or whole code) that is under some license, even if the library is not used, makes you bound to the license for that library.

What about [candiedyaml](https://github.com/cloudfoundry-incubator/candiedyaml), used in Cloud Foundry and under `Apache License v2` (more favorable)?

There is already a reference to the `goraph` library and license, so it makes sense to add this one as well in the `README.md` in case it's going to stick.

**Comment by robdimsdale** [comment]
Yes, I've observed the same thing using godep. It's annoying that it pulls in dependencies even if you don't actually use them. I am also not a legal expert, and I agree that using godep could result in you shipping the code and that might be undesirable, but we don't vendor that code here, and if you're not using the yaml matcher then you don't need the dependency to actually compile against the library and hence you don't have to ship the code.

The Cloudfoundry organization (and Pivotal) have had issues with candiedyaml, and many libraries have switched to using `yaml.v2` - hence why Pivotal teams contributed it to this library. Unless candiedyaml improves we are unlikely to switch to it.

Given the `yaml.v2` library is likely to remain an optional dependency of this project for the foreseeable future, please feel free to update the README with a phrasing of your choice in a PR if you wish.
