### ISSUE TITLE
Test-double library that plays well with gomega?

### ISSUE THREAD

**Issue by xeger** [onsi/gomega#162]
I recently got annoyed at the amount of boilerplate code I need to write in order to mock my interfaces during tests. `vektra/mockery` has provided me with part of the solution, but it's buggy and the codebase is hard to maintain in my experience. Since mockery mandates the use of `stretchr/testify`, I have gotten familiar with that package, too; although it works well and its API is clean, it doesn't play very nicely with ginkgo/gomega. In particular, its assertions have a very `testing` feel to them and don't mix well with gomega matchers. FInally, there is a high degree of overlap between testify's mock expectations and gomega's matchers, adding another layer of confusion.

I'm experimenting with writing my own mock/stub/fake generator now, which will initially output `testify` compatible code, but which I intend to support multiple mocking back ends. That has got me thinking: what would my ideal mocking package look like? I concluded that it would strongly resemble gomega, and perhaps even make use of gomega's matchers to setup expectations about parameters or return values and to avoid reinventing the wheel. Its API would use a tiny onsi-flavored DSL and might blend with gomega like so...

```
type Widget interface {
  DoStuff(int, string) error
}
```

```
import (
  "github.com/xeger/fantasymock"
  "github.com/onsi/gomega"
)

// this type is generated code
// some tool scans otherpkg for all interface definitions and spits out one type def for each, in its own file
// StubWidget has the interface of Widget, but embeds an unexported mock controller
stub := otherpkg.StubWidget{}

// fail when someone tries to do stuff to 5 of any kind of dogs
fantasymock.Allow(stub).ToReceive("DoStuff", 5, gomega.HaveSuffix("dogs")).Return(fmt.Errorf("blah")))
```

This lets me create stubs -- mock objects that do not verify behavior. However, being a recovering Rubyist, I'd also want a way to spy on my objects after the fact, or maybe even to verify behavior inline. I'd want the behavior verification to play nicely with Ginkgo:

```
fantasymock.RegisterFailHandler(ginkgo.Fail)

// this lazy-creates an inner stub object
pureMock := otherpkg.MockWidget{}

// this creates a mock that is actually a proxy to a real object
partialMock := otherpkg.MockWidget{otherpkg.NewWidget()}

fantasymock.Allow(pureMock).ToReceive("DoStuff", 5, "fuzzy cats")
fantasymock.Expect(pureMock).ToReceive("DoStuff", 5, "fuzzy cats")
```

Now, to actually _implement_ this style of behavior verification, I would need fairly deep integration with ginkgo -- to register every mock that anyone created, and to verify all of the expectations at the end of the test case. Also, I am stealing the `Expect` term from ginkgo's DSL, which means that you can't dot-import both packages. Seems messy. Maybe the spy pattern would work better:

```
pureMock := otherpkg.MockWidget{}

otherpkg.ProcessWidget(pureMock)

Expect(pureMock).To(fantasymock.HaveReceived("DoStuff", gomega.BeNumerically(">=", 5), gomega.HaveSuffix("dogs)).And(gomega.Succeed())
```

This seems cleaner to implement, albeit not quite as pretty to code to. It does have tremendously good integration with gomega, though; in fact, its "meat" (`HaveReceived`) is just a gomega matcher.

Anyhow -- my main reason for opening this issue was to get your thoughts on mocks, stubs and BDD in golang. I saw that you'd forked testify and thought you might have an opinion...

**Comment by robdimsdale** [comment]
At Pivotal/CloudFoundry we make pretty heavy use of https://github.com/maxbrunsfeld/counterfeiter - it's simple but powerful, and although the original maintainer has essentially moved away from golang and has no little need for the library, he engages the community. Just a couple of months ago we merged in a couple of non-trivial changes after some good communication.

While it works well with ginkgo and gomega, it doesn't have any dependencies on them, and it sits alongside them; it doesn't hook into any parts of ginkgo or gomega.

**Comment by xoebus** [comment]
@robdimsdale I like `counterfeiter` but I'm wondering if there's a way we can improve look and experience of using Gomega matchers with it. The current `Expect(thing.FunctionCallCount()).To(Equal(1))` is a little long-winded and hard to read.

I tried a while back to abuse the `reflect` package to let this be turned into `Expect(thing.Function).To(HaveBeenCalled(Once())` but I couldn't get it to work satisfactorily. Does anyone who know the `reflect` package know if this would be possible?

**Comment by onsi** [comment]
@xoebus have you seen @tjarratt's https://github.com/tjarratt/gcounterfeiter ?

hey @xeger - perhaps take a look at counterfeiter and gcounterfeiter?  These tend to be the tools we use at Pivotal.  

I'm not too keen of deeply integrating a solution into Ginkgo or Gomega.  However if you _did_ want to build a spy framework (not sure it's possible in Go tbh - the `reflect` package does not let you replace methods) one approach would be to require users to have a top-level 

```AfterEach(func() 
    fantasymock.Validate()
})```

You could even go crazy and have the `fantasymock` package add this `AfterEach` on import but then you'd be super tightly coupled to Ginkgo.  `fantasymock` could then do all the work of tracking spies/mocks/what-have-you.

But take a look at counterfeiter first.  In general while a bit more verbose/boiler-platey I do find explicit fake creation and dependency injection to be easier to reason about.

**Comment by robdimsdale** [comment]
@onsi looks like part of your example and explanation got cut off there

**Comment by onsi** [comment]
thanks @robdimsdale markdown-fail

**Comment by xoebus** [comment]
@onsi woohoo!

**Comment by xeger** [comment]
(g)counterfeiter seem to be just the ticket; thanks for the references!

I'll probably have a stab at my own anyway in order to play with this spy concept. If we confine ourselves to interfaces, spies should be easy -- just make the mock proxy its calls to a real impl of the interface, and record method calls instead of playing them back.

**Comment by xeger** [comment]
FWIW, closing the "issue" since my question is answered.

**Comment by xeger** [comment]
@onsi, @robdimsdale - took a look at Counterfeiter/Gcounterfeiter, but decided to experiment with something more idiomatic (aka coupled to Gomega, I suppose): https://github.com/xeger/mongoose

The generator is modular; it can also spit out testify-compatible code, or with a bit of work, Counterfeiter-style standalone types. I rather like having a shared library for matchers, common mock interfaces, etc, hence https://github.com/xeger/gomuti

Counterfeiter's parsing is much more robust than Testify's. My parsing is hopefully more robust still; I use `loader` to separate wheat from chaff when hunting for interfaces. In practice, I haven't found anything Counterfeiter couldn't parse, so my main claim to fame is as a Gomega add-on.

**Comment by robdimsdale** [comment]
Cool, thanks for sharing. The `gomuti` library looks interesting too - thanks for bring that to our attention.
