### ISSUE TITLE
Matchers for comparing large structs

### ISSUE THREAD

**Issue by timstclair** [onsi/gomega#170]
I wrote a set of matchers for comparing large nested structs and slices over in [Kubernetes](http://kubernetes.io/), and it was recommended that I try to upstream it here: https://github.com/kubernetes/kubernetes/pull/31831. Before I take the time to move the types around and adapt it to your (gomega maintainers) coding conventions, I wanted to confirm whether you're open to this addition.

The goal of these new matchers is to be able to flexibly match large nested structs and slices, as demonstrated here: https://github.com/timstclair/kubernetes/blob/bbb11ed252da75ec4063fdecac79c4adc750959c/test/e2e_node/summary_test.go#L92

Here is a smaller example of what these matchers let you do:
```go
type Foo struct {
  A int
  B bool
  C []Bar
}
type Bar struct {
  Name string
  Foo Foo
}
...
Expect(actualFoo).To(StrictlyMatchStruct(Fields{
	"A": BeNumerically(">=", 10),
	"B": BeFalse(),
	"C": StrictlyMatchSlice(Name, Elements{
		"first": LooselyMatchStruct(
			"Foo": Ignore(),  // etc ...
		),
		"second": LooselyMatchStruct(
			"Foo": Ignore(),  // etc ...
		),
	}),
})
...
func Name(bar interface{}) string {
	return bar.(Bar).Name
}
```

Of course a similar result could be accomplished with helper functions for matching each subtype, but the advantage to my approach is that the structure of the matchers closely resembles the structure of the matched object, making it much more readable, and also more concise for complicated comparisons.

So what do you think? Does this seem like something you would want upstreamed?

**Comment by timstclair** [comment]
Just to clarify: I'm not looking for a code review right now, just whether or not it's worth my time to open a PR here. Thanks!

**Comment by tedsuo** [comment]
I like the concept. I guess my only question for @onsi and others is whether this should be upstreamed into core, or listed in the community section [Wiki](https://github.com/onsi/gomega/wiki).

Just like working with collections, strings, and JSON is considered a core domain of Gomega, working with structs could be considered core. And the approach here looks good to me. 

What portion of the `kubernetes/test/matchers` package are you looking to upstream? There are some overlapping areas: for example, the Slice matchers overlap with the existing Container matchers. And there are other helper functions which may be extraneous , such as NestedError.

I can suggest two options:
- upstream some of it to gomega, keep some of it in kubernetes.
- keep it all bundled together as a 3rd party repo people can link to, and put it in the community matchers section.

Thanks,
-Ted

**Comment by timstclair** [comment]
I could upstream any subset you are interested in, but the one's that I feel work together in a cohesive way are:

- StructMatcher
- SliceMatcher
- PtrMatcher (useful for pointer fields in structs)
- IgnoreMatcher (useful for ignoring fields in structs)

I recognize that you already have some options for matching slices, but (correct me if I'm wrong), there is no mechanism for "fuzzy" slice comparison, i.e. comparing elements with matchers other than equals. I think it could also benefit from being generalized to work for maps & arrays as well.

WRT `NestedError`, it's not strictly necessary, but if you get an error from a deeply nested object it makes it much easier to identify the matcher that failed. Of course, this could also be done with good context messages, but that makes building up a tree of matchers a little more challenging.

Thanks for taking a look!

**Comment by onsi** [comment]
I quite like how expressive this is.  Very cool.

There were a few recent PRs that added the ability to [compose matchers](http://onsi.github.io/gomega/#composing-matchers) - this started moving Gomega in the direction of being able to more easily construct complex/composite matchers out of existing matchers.

The work you've done here feels like the right next step.  I'd be happy to see a PR for this.

I'm uncertain, however, that this should go into the core set of matchers or be a new top-level package under gomega (a la `gexec` and `ghttp`).  The matchers you've built feel a bit more advanced and self-contained and it might be easier for folks to reason about if we grouped them into a separate package that folks could `.` import.

How about a PR that takes that approach and then we could get a feel for whether or not to  just merge them into the [big pile'o'matchers](https://github.com/onsi/gomega/blob/master/matchers.go) or leave them as a separate top-level package.

Also, would you be up for submitting a PR for the [docs](http://onsi.github.io/gomega/) as well?  I know most folks find the godocs adequate but I do think the narrative and example heavy Gomega docs are useful and lend themselves especially well to this sort of more advanced use case.

**Comment by timstclair** [comment]
Sounds good, I can handle the docs as well. Any opinions on the package name? `gstruct`?

**Comment by onsi** [comment]
sure `gstruct` sounds good to me

**Comment by timstclair** [comment]
A couple open TODOs (Add map & array support), but I'd call this issue done.
