### ISSUE TITLE
Use gexec.Build() to target other platforms?

### ISSUE THREAD

**Issue by henryaj** [onsi/gomega#177]
@tinygrasshopper and I have been using `gexec.Build` to build binaries and test them, but sometimes we want to e.g. build a Linux binary, scp it to a remote machine and run it there.

Using `os.Setenv` to set the right env vars for targeting Linux seems a bit awkward. Thoughts on a better way of doing this? I'm happy to PR in a new `gexec.BuildForPlatform` method if there's interest.

Henry

**Comment by onsi** [comment]
`gexec.BuildForPlatform` could work.  Alternatively how about `gexec.BuildWithEnvironment` that takes an additional map of env variables and merges them in before invoking the process?  Likely more flexible?
