### ISSUE TITLE
Pretty print not pretty for json decoded times

### ISSUE THREAD

**Issue by emidander** [onsi/gomega#182]
When a gomega match fails, it pretty prints the object that did not meet the expectation. For a `time.Time` that has been decoded from JSON this will not be pretty, as such times contain lots of time zone information that is irrelevant and hides what's important. Every `time.Time` generates more than 100 rows of output, which for arrays of structs with many times will generate several thousand lines of output when tested with `HaveLen`. Example output:

```
  Expected
      <time.Time>: {
          sec: 63612379114,
          nsec: 614343564,
          loc: {
              name: "Local",
              zone: [
                  {name: "CET", offset: 3600, isDST: false},
                  {name: "CEST", offset: 7200, isDST: true},
                  {name: "CEST", offset: 7200, isDST: true},
                  {name: "CET", offset: 3600, isDST: false},
              ],
              tx: [
                  {when: -1692496800, index: 1, isstd: false, isutc: false},
                  {when: -1680483600, index: 0, isstd: false, isutc: false},
                  {when: 323830800, index: 2, isstd: true, isutc: true},
[... > 100 rows of this!]
                  {when: 2108595600, index: 3, isstd: false, isutc: false},
                  {when: 2121901200, index: 2, isstd: false, isutc: false},
                  {when: 2140045200, index: 3, isstd: false, isutc: false},
              ],
              cacheStart: 1459040400,
              cacheEnd: 1477789200,
              cacheZone: {name: "CEST", offset: 7200, isDST: true},
          },

```

Code to reproduce:

```
        s := StructWithTime{
            T: time.Now().Add(time.Second * -60 * 60 * 24 * 10),
        }

        json.NewEncoder(os.Stdout).Encode(s)

        var buf bytes.Buffer
        Expect(json.NewEncoder(&buf).Encode(s)).To(Succeed())

        var decodedStruct StructWithTime
        Expect(json.NewDecoder(bytes.NewReader(buf.Bytes())).Decode(&decodedStruct)).To(Succeed())
        Expect(decodedStruct.T).To(Equal(""))

```

I would really prefer the pretty printing to have an exception for time.Time, printing it in a readable string format, or at least only include the most relevant information such a sec/nsec.

**Comment by onsi** [comment]
Happy to accept a PR to the `format` package to special case `time.Time`.  One tricky bit is that two seemingly identical time objects could fail to match because of some esoteric difference that isn't represented in an abbreviated format.

**Comment by emidander** [comment]
I created a pull request. The case where the two times differ despite being seemingly identical doesn't feel like a problem to me, especially not now that the matcher (BeTemporally) agrees with what the pretty printing prints. If one wants to compare detailed time zone information one can still do that using more explicit matching.
