### ISSUE TITLE
a matcher that applies a predicate to all members of a slice/array/other collection, folding with AND

### ISSUE THREAD

**Issue by jraqula** [onsi/gomega#184]
If I have something like:

```
type A interface {
    Field() string
}

var b []A
// populate b ...
```

I would like to be able to write an assertion that is something like:

```
Expect(b).To(OnlyContain(WithTransform(A.Field), Equal("entry")))
```

which would pass if and only if every element of `b` returns "entry" when called `Field()`. Is there a current way to do this with existing matchers? If not, what do you all think of this as an addition?

**Comment by jraqula** [comment]
glancing at the code, this would look just like the contains_element_matcher but with this exit condition inverted (hence "fold with AND" in the title, where contains_element_matcher folds with OR) https://github.com/onsi/gomega/blob/master/matchers/contain_element_matcher.go#L42-L44

**Comment by jraqula** [comment]
@onsi ah, this is helpful. it seems however that this construction doesn't let me write one matcher that should match every element in the slice, on account of this section https://github.com/onsi/gomega/blob/master/gstruct/elements.go#L92-L95 where there can only be one value per string key, and each matcher I provide is paired with one such key -- whereas I would like to declare one condition that should be true of every element in the slice. Do you have any examples of doing this with MatchAllElements/MatchElements?

**Comment by onsi** [comment]
@timstclair wdyt?

**Comment by timstclair** [comment]
Yes, I think allowing duplicate elements is a good idea, as long as it's an option (like `IgnoreExtras` and `IgnoreMissing`). From there it's easy to express the desired "match every element", and the library could optionally provide some convenience methods for it.

**Comment by onsi** [comment]
@jraqula waddaya think?  Would you be up for a PR?

**Comment by jraqula** [comment]
one PR coming right up!

**Comment by onsi** [comment]
woot!  thanks :) an update to the docs on gh-pages to go along with the PR would be great too!

**Comment by jraqula** [comment]
will do! also, a note just to decide on what to call the flag -- I've considered these options:
- `IgnoreKeyConflicts`, indicating that the matcher for a particular key can be allowed for multiple members, and to keep with the `Ignore####` pattern of the other two
- `AllowMultipleMatches`, which I like slightly more just because it expresses more clearly that the key function and the matcher function are both intended to describe groups of members

any preference/alternative?

**Comment by onsi** [comment]
i like the AllowMultipleMatches option

**Comment by timstclair** [comment]
I think `Ignore*` could be interpretted as ignoring (i.e. not matching) additional elements, so I agree Allow is better.

`AllowDuplicates` is a little less wordy.
