### ISSUE TITLE
Bug: incorrect matching of string-valued errors

### ISSUE THREAD

**Issue by rickb777** [onsi/gomega#189]
In match_error_matcher.go:24

	if isString(matcher.Expected) {
		return reflect.DeepEqual(actualErr.Error(), matcher.Expected), nil
	}

should be

	if isString(matcher.Expected) {
		return actualErr.Error() == matcher.Expected, nil
	}

because the error in question may have internal structure that should be ignored in the case of calling Error(). This is necessary to behave according to the published description

> EXPECTED can be a string, in which case ACTUAL.Error() will be compared against EXPECTED.

(ref Git master:f1f0f388b31eca4e2cbe7a6dd8a3a1dfddda5b1c)

**Comment by rickb777** [comment]
Workaround: use a longhand form like this:

	_, e := MethodUnderTest()
	Ω(e.Error()).Should(Equal("expected error message"))

**Comment by onsi** [comment]
makes sense - are you up for submitting a quick PR for this?

**Comment by jvshahid** [comment]
@wfernandes I don't see a test for the code you just pushed. In fact, I'm not convinced that anything need to change. According to [DeepEqual](https://golang.org/pkg/reflect/#DeepEqual) docs, string values are DeepEqual if they are equal using go's equality `==` operator.

**Comment by wfernandes** [comment]
@jvshahid The test already existed. It was just a simple refactor to get my fingers wet for contribution. I also did it for simplicity and readability.

**Comment by jvshahid** [comment]
I am not too worried about the change. I am just trying to understand the change in behavior that was requested in this issue and couldn't find a test to illustrate it. which test are you referring to @wfernandes ?
