### ISSUE TITLE
Make string equality diff comparison user-configurable

### ISSUE THREAD

**Issue by ericTsiliacos** [onsi/gomega#192]
As of pr #190 the `Equal` matcher attempts to diff long strings. We should make this configurable so users can get more information when they need it.

One suggestion: put something in `format.go` like `MaxDepth` that allows users to change this behavior. This would be consistent with the current approach.

Another suggestion: use the builder pattern on the EqualMatcher to set some relevant configuration closer to the site of the matcher.

**Comment by scottschulthess** [comment]
I'm comparing strings of around 20 characters using Equals and it's not showing a diff, but it would be nice to be able to turn it on

**Comment by onsi** [comment]
Make sense.  @scottschulthess @ericTsiliacos either of you up for a  PR to `format.go` that mirrors what `MaxDepth` does?  Would want an update to the docs (this section: http://onsi.github.io/gomega/#adjusting-output) on the `gh-pages` branch too.

**Comment by onsi** [comment]
Make sense.  @scottschulthess @ericTsiliacos either of you up for a  PR to `format.go` that mirrors what `MaxDepth` does?  Would want an update to the docs (this section: http://onsi.github.io/gomega/#adjusting-output) on the `gh-pages` branch too.
