### ISSUE TITLE
Allow optionalDescription to be a function in Expect().To()

### ISSUE THREAD

**Issue by tamasd** [onsi/gomega#193]
It would be nice if I could call `Expect().To()` with a `func() string` as an optionalDescription parameter. This function would be evaluated only if the assertion fails.

My exact use case is that I do an HTTP request and assert the response code first, and if that fails, I would like to dump the body to stdout for easier debugging.

Currently I do it with a boolean variable and a defer, but it would be great to have a cleaner solution.

**Comment by williammartin** [comment]
Sorry it took so long to get a response. This seems sensible and not sure it's too tricky. The relevant code is here: https://github.com/onsi/gomega/blob/master/internal/assertion/assertion.go#L46-L53 and it already takes `interface{}`. I guess maybe we'd only want to [build the description](https://github.com/onsi/gomega/blob/master/internal/assertion/assertion.go#L57) on failure in the case of a function.

Happy to review a PR for this, thanks.
