### ISSUE TITLE
Making a 1.1 release soon? 

### ISSUE THREAD

**Issue by codeasone** [onsi/gomega#194]
I'm vendoring `gomega` into my project using `glide` and it insists on using the `1.0` from back in 2014, regardless of efforts to coerce the tooling into using current `HEAD` via the `glide.lock` for example.

Any chance of making a `1.1` release soon?

**Comment by codeasone** [comment]
I've mitigated this by forcing `glide` to use recent HEAD via: 

```
- package: github.com/onsi/gomega
  vcs: git
  ref: e85f63af4302dc0e4277c6008ecf803f1d80e4f0
```

**Comment by robdimsdale** [comment]
@codeasone as there have been a `1.1.0` release made recently I will close this issue.
