### ISSUE TITLE
Expect().NotTo(BeNil()) does not work as expected

### ISSUE THREAD

**Issue by jawnsy** [onsi/gomega#195]
I'm not sure if this is a bug, or if I'm just not understanding Go :smile:

I have assertions like these:

```go
var x *api.SupplementalPlan
gm.Expect(x).NotTo(gm.BeNil(), "x is nil")

gm.Expect(nil).NotTo(gm.BeNil(), "nil is nil")
```

I'd expect them to fail, since we were expecting the value not to be `nil`, but, well, it's `nil`. In my actual test it's a pointer to a struct variable (which happens to be `nil`), so further down I get a nil pointer panic. I've tried using gomega master and it has the same problem.

Looking at the gomega code, I can't understand why it's not working as we expect. The matcher [checks isNil](https://github.com/onsi/gomega/blob/d59fa0ac68bb5dd932ee8d24eed631cdd519efc3/matchers/be_nil_matcher.go#L8) and the implementation of type_support.go's [isNil looks perfectly reasonable](https://github.com/onsi/gomega/blob/d59fa0ac68bb5dd932ee8d24eed631cdd519efc3/matchers/type_support.go#L165). If I had to hazard a guess, I might be misunderstanding how the [reflection code](https://github.com/onsi/gomega/blob/d59fa0ac68bb5dd932ee8d24eed631cdd519efc3/matchers/type_support.go#L170-L173) (lines 170-173) actually works.

**Comment by jawnsy** [comment]
Well, I can't explain it, but if I add this to be_nil_matcher_test.go: `Expect(nil).NotTo(BeNil())`, then I get a test failure as expected when running `go test`. Any ideas?

**Comment by jawnsy** [comment]
I wonder if it's because we're using gomega (without ginkgo) with XUnit style tests. We aren't registering any fail handler, but the example docs don't do it either. We use (and love) ginkgo for some other tests, so maybe the answer is that we need to adopt ginkgo here as well.

As another data point, also tried this - it doesn't fail immediately as I expected:

```go
func testResourceAddonReentrancy(t *testing.T, h *testHarness) {
	gm.RegisterTestingT(t)
	gm.Expect(false).To(gm.BeTrue())
```

Our suite is defined like this:

```go
func TestIntegration(t *testing.T) {
	h := newTestHarness(t)
	t.Run("ResourceAddonReentrancy", func(t *testing.T) { testResourceAddonReentrancy(t, h) })
```

**Comment by tony-spataro-rs** [comment]
This is due to gomega calling `T.Fail` (which continues to run the test) rather than `T.Fatal` (which would halt test execution immediately).

A fix was merged to gomega's master branch in mid May: https://github.com/onsi/gomega/pull/215

If you update to the latest gomega and try again, it should fail immediately as you expect.

**Comment by jawnsy** [comment]
@tony-spataro-rs Awesome, thanks for letting me know about that fix. Unfortunately, I no longer have access to the affected codebase, so I can't test - I suppose the best way to proceed now is simply to close this issue. Thanks to @jim-slattery-rs for tracking this down and fixing it! 👍 💓
