### ISSUE TITLE
MatchJSON fails to detect differences

### ISSUE THREAD

**Issue by sfriedel** [onsi/gomega#204]
I noticed some of our tests passing even though they shouldn't. Seems like it was introduced in 2d470dc13f066a6dcf7a091834e7d9d38e9f0df5 since with 1de7ab2df9105aa5c15c4d7e14a8a514e3cb8d4b those tests correctly fail. 

Small test case that shows the behavior:

```go
var _ = Describe("Example", func() {
	It("should fail", func() {
		actual := `
		{
			"a": null,
			"b": null
		}`
		expect := `
		{
			"c": "c",
			"d": "d"
		}`
		Expect(actual).To(MatchJSON(expect))
	})
})
```

This test passes even though it clearly shouldn't since the JSONs differ.

**Comment by onsi** [comment]
Welp, looks like this was introduced in #201 

hey @madamkiwi and @wendorf looks like you're missing an edge case.  Am going to revert the PR for now as it breaks the cardinal rule of a matcher library: "Thou shalt not return a false positive"

**Comment by onsi** [comment]
OK have reverted the commit.  please confirm that it works and close this out @sfriedel

**Comment by wendorf** [comment]
Sorry about that! Thanks for catching the issue. We'll get some better test suites and resubmit the change.

**Comment by sfriedel** [comment]
I can confirm that reverting solved the issue. Thanks for the quick fix and for all your hard work on this library :+1:
