### ISSUE TITLE
MatchXML is not working with non UTF-8 xml inputs

### ISSUE THREAD

**Issue by aubm** [onsi/gomega#211]
Something like [this](https://github.com/aubm/gomega/commit/5f21b5091ba78609ce0689279370c4136f6b3179) would do the trick but it requires an import to this external package: https://godoc.org/golang.org/x/net/html/charset

For information, the source is available here: https://go.googlesource.com/net/+/master/html/charset/

**Comment by onsi** [comment]
My preference would be to not add any external dependencies.  it's shocking how many builds that can break :/

options:
- we add an `extensions/xmlmatcher` package under the root tree
- pull MatchXML into a separate repo and update docs to point at it

thoughts?

**Comment by aubm** [comment]
I agree,

Neither solution is perfect but I think I'm more comfortable with a separate repo.

What do you think?
Do you want me to create this repo, or do you want to create it under the same namespace as gomega for people to find it easier?

**Comment by onsi** [comment]
go ahead and create it @aubm and we can link to it from the community matchers section in the wiki:
https://github.com/onsi/gomega/wiki

**Comment by aubm** [comment]
I just realized that Gomega already depends on an external package [here](https://github.com/onsi/gomega/blob/master/matchers/match_yaml_matcher.go#L9) for the `MatchYAML` matcher.

I already started the migration to the new repository so it doesn't bother me to continue. But should we reconsider the approach?

**Comment by onsi** [comment]
ok let's put it in Gomega on master.

**Comment by aubm** [comment]
Closed by https://github.com/onsi/gomega/pull/212
