### ISSUE TITLE
Arrays with objects not matched in MatchJSON

### ISSUE THREAD

**Issue by gmartsenkov** [onsi/gomega#217]
Hi all!

I'm having an issue where a JSON has an array property with objects, but their order can change and my tests, therefore, fail randomly. I'm not sure if this is expected behavior or not. Does anyone know of a workaround?

Cheers

This is a duplicate of #208

**Comment by onsi** [comment]
Yes, an array is an ordered container so an assertion *should* fail if the expected order of the contents of the array do not match the actual order of the contents of the array.

To get around this you need to decode the JSON object and either match its various components or use the [gstruct](http://onsi.github.io/gomega/#gstruct-testing-complex-data-types) subpackage to test the hydrated objects.  In both cases the `ConsistOf` matcher allows you to assert that an array/slice contains the expected objects in _any_ order.

**Comment by jontonsoup** [comment]
For usability sake it might be interesting to add a flag or function that tests arrays in an order independent way. Similar to the the type conversion matchers. `BeEquivalentTo`

**Comment by onsi** [comment]
That _does_ exist - it's the [ConsistOf](http://onsi.github.io/gomega/) matcher.  I don't think it make sense to add complexity to Gomega's `MatchJSON` matcher.  If you've got complex JSON or are trying to make equality assertions beyond strict equality (which would include guaranteeing array order) I think you will have less surprising and more readable tests if you hydrate the object and use explicit matchers and/or the [gstruct](http://onsi.github.io/gomega/#gstruct-testing-complex-data-types) package.

Consider, for example:

```
JSONToVerify := "[
    {
        "name": "U2",
        "discography": ["Boy", "October", "War", "Under a Blood Red Sky", ...]
    },
    {
        "name": "Fleetwood Mac",
        "discography": ["Fleetwood Mac", "Mr. Wonderful", "Then Play On", "Klin House",...]
    }
]"
```

You may not care about the order of the top level array.  But you almost certainly do care about the order of the `"discography"` arrays as it carries information.

I'd test this, this way:

```
var artists []Artist

Expect(json.Unmarshal(JSONToVerify, &artists)).To(Succeed())
Expect(artists).To(ConsistOf(u2Fixture, fleetwoodMacFixture))
```

**Comment by gmartsenkov** [comment]
Thanks a lot guys! I'm quite new to Go(I'm usually a Ruby dev), and I must say I really enjoy using this library!
