### ISSUE TITLE
Expanded Json and Yaml matcher

### ISSUE THREAD

**Issue by Benjamintf1** [onsi/gomega#220]
Extra options for list ordering and a ContainsJson/Yaml options. Its allowed by a drop-in replacement for reflect.deepEqual()

https://github.com/Benjamintf1/Expanded-Unmarshalled-Matchers

**Comment by onsi** [comment]
Perfect - thanks!  Added this to the Wiki and to the MatchJSON documentation on http://onsi.github.io/gomega/
