### ISSUE TITLE
Better handling for `func() (foo, bar, baz, error)`

### ISSUE THREAD

**Issue by decibel** [onsi/gomega#221]
This is a really common pattern: a function that returns an arbitrary number of values, and finally an error, and if there's an error all return values will be their zero value (except obviously the final error value).

It would be really nice if there was some way to do a single call that verifies that all return values are their zero value, and the final error value matches what you want.

I guess the best way to handle that would be a different form of Expect()?

(See also #106)

**Comment by williammartin** [comment]
Hey @decibel sorry no one looked at this. I think there is a lot of hidden complexity here and I'm not sure I want to introduce it into the core but for discussions sake, if you could have whatever UX / API you wanted for this, what would you like to see?

The only way I think this could be done right now is to Expect on the function with a custom matcher e.g.

```
myFunc := func() (string, string, string, nil) {
    return "", "", "", errors.New("boom")
}

Expect(myFunc).To(HaveZeroValuesAndError())
```

With a custom matcher that called the function and asserted on the return values. Not a particularly elegant or portable solution perhaps though.

**Comment by williammartin** [comment]
I'm going to close this due to lack of response. If anyone would like to reopen please be my guest!
