### ISSUE TITLE
A function to advance the gexec buffer

### ISSUE THREAD

**Issue by Benjamintf1** [onsi/gomega#224]
Could we have a function to advance the curser of the gexec buffer to the end unconditionally, without having to provide a buffer of the size of the contents. Maybe something like:

```
func (b *Buffer) Advance() {
       b.lock.Lock()
       defer b.lock.Unlock()
       b.readCursor = size(b.contents)
       return
}
```
Then you can be sure between tests that the buffer has been advanced/you are not leaking between tests.

**Comment by jvshahid** [comment]
@Benjamintf1 I am not sure I understand the use case. Can you provide some code that demonstrate your use case, in particular why is advancing the buffer necessary as opposed to creating a new buffer for each test

**Comment by williammartin** [comment]
@Benjamintf1 bump

**Comment by Benjamintf1** [comment]
Oh, I'm terribly sorry. If creating a process takes a long time, you would do it sometimes in the suite instead of the before-each. In that case, it would be valuable to be able to advance the buffer to ensure no test pollution.

**Comment by jvshahid** [comment]
I am still not clear what is the use case here. If you are trying to avoid test pollution why can't you use a different buffer ?

**Comment by Benjamintf1** [comment]
The buffer is the one that comes from starting a process with gexec.

**Comment by jvshahid** [comment]
I get it, but why are you sharing the session instead of creating a different process for each test.

**Comment by Benjamintf1** [comment]
Because of time(process startup as well as it's dependancies) as well as less shareable dependancies.

**Comment by Benjamintf1** [comment]
@jvshahid It's not a huge deal, and we haven't been working in that area in a while, i just figured it might be convenient for long startup processes if you want to do integration level testing around logging. Feel free to close it whenever you want.

**Comment by jvshahid** [comment]
@williammartin thoughts ?

**Comment by williammartin** [comment]
I'm not a fan of `Advance()`, I think it is a bit confusing and it's also going to fill up an in memory buffer with junk. However, I think I get the practical use case, so it would be good if we had something to solve here.

If I understand @Benjamintf1 correctly, the real crux of this is avoiding test pollution, when sharing the same session.

What do you think of something like:

```
func (b *Buffer) Clear() {
	b.lock.Lock()
	defer b.lock.Unlock()

	b.contents = []byte{}
	b.readCursor = 0
}
```

Not sure that code is exactly right, but hopefully you get the point.

**Comment by Benjamintf1** [comment]
I think that should work
