### ISSUE TITLE
Incorrect results for strings that are errors

### ISSUE THREAD

**Issue by kaedys** [onsi/gomega#232]
I've recently started using Dave Cheney's method of making [constant package-level errors](https://dave.cheney.net/2016/04/07/constant-errors) by defining a named `string` type that implements the `error` interface.  However, when one tries to compare these using the `MatchError` matcher, it reports a false mismatch.  For example:

```
type Error string
func (e Error) Error() {
    return string(e)
}

const ErrFail Error = "failed"

func Foo() error {
    return ErrFail
}

var _ = Describe("Example", func() {
    It("compares equal errors", func() {
        Expect(Foo()).To(MatchError(ErrFail))
    })
}
```
This fails with a relatively useless error message:

    Expected
        <example.Error>: failed
    to match error
        <example.Error>: failed

Digging down, this is because `matchers.MatchErrorMatcher.Match()` (match_error_matcher.go:25-31) checks if the two values are strings _before_ it checks if they are errors, despite the matcher being an _error_ matcher first and foremost.

```
	if isString(matcher.Expected) {
		return reflect.DeepEqual(actualErr.Error(), matcher.Expected), nil
	}

	if isError(matcher.Expected) {
		return reflect.DeepEqual(actualErr, matcher.Expected), nil
	}
```

When this happens, reflect, instead of being given two identical named string types, is instead given the named string type and the _string_ version of the same named string type, which of course fails the deep equal due to type inequality.  If these two if statements are reversed, so the error type is checked first, it works as expected.

**Comment by gcapizzi** [comment]
Given the only thing that makes a type an `error` type in Go is the `Error() string` method, shouldn't we compare error exclusively through the `Error() string` return value?
Shouldn't two `error`s with different implementation but same return value for `Error()` be considered equal?
WDYT @onsi?

**Comment by kaedys** [comment]
That's a valid argument.  Part of the problem, though, is that the _Expected_ value is not cast to a simple string before being matched as such.

That said, I do think there is value in being able to compared _types_ of errors.  The error type itself is just an interface, and there's validity to asserting that the type actually fulfilling that interface is this other expected type, especially in codebases that used typed errors as a way of communicating (such as ability to retry the given action).  These cases require checking the type information of the error, not just the string output.

The existing MatchError matcher already supports this type of comparison, in that if the Expected is of type string, the string output of the actual error's Error() method will be compared instead.  It just also allows the errors themselves to be compared including type information.  What I'm proposing is that if the provided Expected item is _both_ an `error` and a `string`, then the `error` qualification should take priority over the `string` qualification.

**Comment by kaedys** [comment]
@onsi if I submitted a PR swapping those two conditionals, do you have any reservations about accepting it?

**Comment by onsi** [comment]
Yes feel free to swap them!

**Comment by kaedys** [comment]
Roger that, I'll try to get a PR in this weekend for it.

**Comment by kaedys** [comment]
PR submitted, what's our next step on this?  I'd love to get this merged so I can remove my janky workaround in our code.

**Comment by kaedys** [comment]
Thanks much!
