### ISSUE TITLE
Any way to MatchJSON and ignore keys that aren't in expected?

### ISSUE THREAD

**Issue by treeder** [onsi/gomega#236]
eg: 

I'd like this to pass:

```
expected: {"name": "John Doe"} got: {"id": "1", "name": "John Doe"} 
```

**Comment by williammartin** [comment]
Hi @treeder.

There's no way to do this with MatchJSON as it does a `deepEquals` expectation: https://github.com/onsi/gomega/blob/master/matchers/match_json_matcher.go#L31

You consider using [gstruct](https://onsi.github.io/gomega/#gstruct-testing-complex-data-types) to do assertions on the unmarshaled struct, or we could have a look at whether this behaviour would fit into a JSON Matcher.

**Comment by Benjamintf1** [comment]
You could also use https://github.com/Benjamintf1/Expanded-Unmarshalled-Matchers. It has Contains Json and various other options.

**Comment by williammartin** [comment]
Thanks @Benjamintf1. Think we might pull those matchers into Gomega if you are alright with it? I know you opened a PR a long time ago.

**Comment by williammartin** [comment]
I'm going to close this out and if we want a separate issue to pull in those matchers we can do so. Thanks all.
