### ISSUE TITLE
The Ω of Ω assertions in Ω tests

### ISSUE THREAD

**Issue by williammartin** [onsi/gomega#244]
Ω is self perpetuating. Adding tests and adhering to conventions means using Ω. Let's wholesale, or suite-by-suite get rid of Ω assertions in favour of `Expect`.

It would be really great if we could fix this in the [docs](https://onsi.github.io/gomega/) too.

**Comment by onsi** [comment]
Melancholy sigh
It is time to say goodbye
Farewell Ω

**Comment by williammartin** [comment]
Looks like we can perhaps use something like:

```
for pattern in \
    'Ω(a).Should(b) -> Expect(a).To(b)' \
    'Ω(a).Should(b, c) -> Expect(a).To(b, c)' \
    'Ω(a).ShouldNot(b) -> Expect(a).NotTo(b)' \
    'Ω(a).ShouldNot(b, c) -> Expect(a).NotTo(b, c)' \
    'Ω(a).To(b) -> Expect(a).To(b)' \
    'Ω(a).ToNot(b) -> Expect(a).NotTo(b)' \
    'Ω(a).NotTo(b) -> Expect(a).NotTo(b)' \
; \
do find . -name '*.go' -a -not -path '*/Godeps/*' | xargs gofmt -w -r "${pattern}"; done
```

to achieve this...

**Comment by james-lawrence** [comment]
just going to leave this here: `https://godoc.org/golang.org/x/tools/cmd/eg`

**Comment by Benjamintf1** [comment]
https://github.com/onsi/gomega/pull/268
