### ISSUE TITLE
XUnit test parallel execution

### ISSUE THREAD

**Issue by smyrman** [onsi/gomega#254]
To quote the documentation:

> Gomega uses a global (singleton) fail handler. This has the benefit that you don’t need to pass the fail handler down to each test, but does mean that you cannot run your XUnit style tests in parallel with Gomega. If you find this odious, open an issue on Github and let me know.

Gomega appears to be a pretty decent matcher library, but it would be nice to get better parallel execution support when using XUnit tests, e.g. allowing the initialization of a handler instance:
```go
 m := gomega.NewTHandler(t)
 m.Expect(something).To(gomega.BeNil())
```

**Comment by rosenhouse** [comment]
Yes please.  I would really like to use Gomega in a project that has XUnit-style tests, but I'm hesitant to introduce this patterns, since it cannot be used in parallel tests.

**Comment by onsi** [comment]
I just pushed a change to master that fixes this and updated the docs.  Assuming a `.` import you can now:

```
g := NewGomegaWithT(t)
g.Expect(foo).To(BeNil())
g.Eventually(foo).Should(Equal("bar"))
g.Consistently(foo).Should(Equal("bar"))
```

**Comment by rosenhouse** [comment]
This works great, thank you!

**Comment by onsi** [comment]
Great thanks!  @smyrman wdyt?

**Comment by rosenhouse** [comment]
Just remember to (re-) initialize your `g` inside any subtests, e.g.

```go
func TestConfigLoadMissingRequiredFields(t *testing.T) {
	requiredFieldNames := []string{
		"ServerCACertPath",
		"ClientCertPath",
		"ClientKeyPath",
		"Address",
		"PollInterval",
	}
	for _, n := range requiredFieldNames {
		fieldName := n // don't close over the iterator
		t.Run("required field "+fieldName, func(t *testing.T) {
			g := gomega.NewGomegaWithT(t)
...
```

**Comment by smyrman** [comment]
@onsi, this looks like the right interface to me - looking forward to test it after the holidays 👍

**Comment by rosenhouse** [comment]
@onsi any chance you could cut a release with this commit?  the downstream project I'm contributing to prefers that their dependencies be referenced by tag name.  thanks!

**Comment by williammartin** [comment]
@onsi Please loop me in if you do ^

Also, I couldn't find the documentation referenced in the issue, just want to make sure everything got updated as necessary.

**Comment by onsi** [comment]
can do - but can't get to it till tonight at the earliest.  I'll write up instructions for how to do it and commit them as well that way other committers can own this, too and we can iterate on it

**Comment by zachgersh** [comment]
hey @williammartin - I think it is probably safe to close this now?

**Comment by rosenhouse** [comment]
Yes, this issue is fixed.

**Comment by williammartin** [comment]
Sweeeeet. Thanks all.
