### ISSUE TITLE
Panic matcher for a specific value.

### ISSUE THREAD

**Issue by jmalloc** [onsi/gomega#257]
Is there an existing way to assert that a function panics with a specific value? I've had a look through the docs and source and couldn't see anything.

If not, would a PR for such a feature be welcome?

I'm picturing usage something like:

```go
Expect(fn).To(PanicWith(Equal(expected)))
```

I've put together a [quick and dirty prototype](https://gist.github.com/jmalloc/73882599fa705b8d098b9bcdf4544bc5) which works but the failure messages are not particularly great.

**Comment by williammartin** [comment]
I think you're right, the only `panic` matcher we have is generic and can't assert on message: https://onsi.github.io/gomega/#panic

I think this would be a reasonable PR for something to include in the core matchers. I do wonder if it would be better following the pattern of `MatchError` https://onsi.github.io/gomega/#matcherrorexpected-interface e.g.

```
Expect(fn).To(MatchPanic(expected))
```

Not convinced but I can see an argument for consistency. Let's hash it out :)

**Comment by jmalloc** [comment]
> I do wonder if it would be better following the pattern of MatchError

Are you referring solely to the naming of the function, or suggesting having the matcher accept a string message instead of another matcher?

On the chance it's the latter, I think it's important to allow a "sub-matcher",  as `panic()` accepts `interface{}` not only a string or error, even though I'd guess that those would be the two most common usages by far.

The expression below would still be possible, though I admit that it reads terribly 😞 

```go
Expect(fn).To(PanicWith(MatchError("message")))
```

> I guess I don't like when I see MatchError with an `ACTUAL` as function type

FWIW I agree. My gut feeling as a user is that the `Panic...` prefix is desirable. As best I can tell it's only the use of `Panic()` which causes `ACTUAL` to be evaluated as a function so the `PanicWith()` naming offers some consistency of its own.

**Comment by khuddlefish** [comment]
Our team has developed a function that does that for our own testing though it doesn't fit the interface. We would either be interested in contributing to the effort or using whatever you end up with if you get something added :)

**Comment by williammartin** [comment]
@khuddlefish What does your interface look like?

@jmalloc I just meant instead of `PanicWith` it would be `MatchPanic`, but I've sort changed my mind on that, because `PanicWith` makes a lot more sense in the context of `ACTUAL` being a function. 

I'm not in love with `PanicWith` because it can read weirdly, but it's best we've got so far. Definitely think it's useful and maybe we can hash out a name later if you'd like to PR.

**Comment by khuddlefish** [comment]
@williammartin What we do is `defer testutils.ShouldPanicWithMessage("expected message")` before calling the function we expect to panic. It does a recover and looks at the output. We didn't exactly have matchers in mind when we wrote it though. Also, I like the `PanicWith` syntax as well.

**Comment by williammartin** [comment]
We were wondering if `PanicWithValue` might be a reasonable compromise. WDYT?

**Comment by jmalloc** [comment]
To my mind `PanicWithValue` implies that only an equality comparison can be performed on the panic value. The prototype in [the gist](https://gist.github.com/jmalloc/73882599fa705b8d098b9bcdf4544bc5) accepts a "sub-matcher", though the current naming is definitely awkward.

Just to throw some examples out there side-by-side:

- `Expect(fn).To(PanicWithValue(HavePrefix(p)))`
- `Expect(fn).To(PanicWith(HavePrefix(p)))`
- `Expect(fn).To(PanicMatching(HavePrefix(p)))`
- `Expect(fn).To(Panic(HavePrefix(p)))` -- perhaps `Panic()` could become variadic to accept an optional sub-matcher?
- `Expect(fn).To(Panic().ValueMust(HavePrefix(p))))` -- Now I'm just being silly!

Regardless of the naming, I'll work on a proper PR as time permits :smiley: I may need some assistance working out how to produce more meaningful failure messages. The prototype simply uses the sub-matcher's failure messages, which doesn't give any feedback about the fact that a panic was expected at all.

**Comment by williammartin** [comment]
@jmalloc Did you ever have a think about a PR for this? Do you still use gomega/is it still valuable to you?

**Comment by williammartin** [comment]
@jmalloc Any thoughts around a PR for this?

**Comment by jmalloc** [comment]
I'm sorry, I never got a chance to look into this any further. I do still use Gomega, and I imagine this would still be a useful addition.
