### ISSUE TITLE
*gexec.Session panics when session.Command.Process is nil

### ISSUE THREAD

**Issue by hoegaarden** [onsi/gomega#258]
The [`Kill()`](https://github.com/onsi/gomega/blob/003f63b7f4cff3fc95357005358af2de0f5fe152/gexec/session.go#L157) and [`Signal()`](https://github.com/onsi/gomega/blob/003f63b7f4cff3fc95357005358af2de0f5fe152/gexec/session.go#L194) methods call methods on `session.Command.Process` -- the `Process` can however be nil which leads to a panic.

In slack we discussed whether this panic is reasonable -- does it only even happen in situations in which you want the test to fail anyway? 

The answer is "no". Consider the following code:
```go
var (
  thing1 *gexec.Session
  thing2 *gexec.Session
)
AfterEach(func(){
  // Ensure all the things are stopped
 thing2.Terminate()
 thing1.Terminate()
})
It("has a sensible lifecycle", func(){
  thing1.Start()
  thing2.Start()

  // Point 1
  Expect(allMyThings.AreUp()).To(BeTrue()) 

  thing2.Terminate()
  thing1.Terminate()

  Expect(allMyThings.AreDown()).To(BeTrue())
})
```

The test tries to bring down both `thing`s. If the expectation at "Point 1" fails, because `thing2` could not be started (`thing1` however could!), we want `thing1` to be shut down before the test stops executing, hence the `AfterEach`.

If the expectation at "Point 1" succeeds, we want to go on to check that we can shut down both things cleanly, and leave the system in the state we expect.

If the `Terminate()` method returned an error instead of panicing, this test would be even clearer:

```go
var (
  thing1 *gexec.Session
  thing2 *gexec.Session
)
AfterEach(func(){
  // Ensure all the things are stopped. If they're already stopped ignore the errors
 thing2.Terminate()
 thing1.Terminate()
})
It("has a sensible lifecycle", func(){
  thing1.Start()
  thing2.Start()

  // Point 1
  Expect(allMyThings.AreUp()).To(BeTrue()) 

  Expect(thing2.Terminate()).To(Succeed())
  Expect(thing1.Terminate()).To(Succeed())

  Expect(allMyThings.AreDown()).To(BeTrue())
})
```

**Comment by nodo** [comment]
Fixed in https://github.com/onsi/gomega/pull/259
