### ISSUE TITLE
BeNumerically over a slice

### ISSUE THREAD

**Issue by reiinakano** [onsi/gomega#260]
I'm trying to compare the equality of two slices but I can't use `Equal` since there are rounding errors.
```
ConsistOf(
    BeNumericallyEqual("~", 3),
    BeNumericallyEqual("~", 4),
)
```

works but doesn't take into account order of the elements. 

Couldn't find anything else similar so had to build my own custom matcher. Is there a better way I'm not seeing?

**Comment by nodo** [comment]
Hi @reiinakano,

Just to double check, am I right to assume that you are trying to test the equality of slices of different types right? `Equal`, will work correctly if the two slices are the same types (see [docs](https://onsi.github.io/gomega/#equalexpected-interface)).

A possible approach could be:
```go
It("suceeds", func() {
	a := []float32{1.0, 2.5, 3.0, 4.1}
	b := []float64{1.0, 2.5, 3.0, 4.1}
	
        Expect(a).To(HaveLen(len(b)))
	for i := range a {
		Expect(a[i]).To(BeNumerically("~", b[i], 3))
	}
})
```

If this doesn't work for you, feel free to post an example to better understand your particular issue.

**Comment by nodo** [comment]
Hey @reiinakano, I am closing this issue for now. Feel free to re-open if you still have issues.
