### ISSUE TITLE
Matching structs based on fields in struct

### ISSUE THREAD

**Issue by haichuanyu** [onsi/gomega#284]
Similar to func HaveKeyWithValue, but applicable to any user defined struct.

//HaveFieldWithValue succeeds if actual is a struct with the passed in field and value.
//HaveFieldWithValue fails if struct is nil, does not contain field, or if value in field is not equal or nil.
//    Expect(mystruct{"Foo": "Bar", "BazFoo": "Duck"}).Should(HaveFieldWithValue("Foo", "Bar"))
//    Expect(mystruct{"Foo": "Bar", "BazFoo": "Duck"}).Should(HaveFieldWithValue(MatchRegexp(`.+Foo$`), "Bar"))
func HaveFieldWithValue(key interface{}, value interface{}) types.GomegaMatcher {
...
}

**Comment by williammartin** [comment]
Hi @haichuanyu, I'm not sure I understand what this improves over:

```
Expect(myStruct.Foo).To(Equal("Bar"))
```

etc. 

Are you expecting a struct you don't know the fields of? If so I would suggest using `BeAssignableToTypeOf` and casting.

**Comment by haichuanyu** [comment]
I am getting an array of struct back from a database query and I want to see if one of them contains a struct with a specified ID. So I can't use the Equals comparator. I have:

`Expect(myStructArray).To(ContainElement(HaveKeyWithValue("Id", 12345))`

**Comment by williammartin** [comment]
Right, I meant use `BeAssignableToTypeOf`, then cast then use the `Equal` matcher but I see now that you want to nest the matchers in a way that won't work.

**Comment by haichuanyu** [comment]
So... do you want me to submit a pull request? What do we do now? It would be cool if I could use this before the end of the week.

**Comment by onsi** [comment]
@haichuanyu have you looked at the `gstruct` package?  Docs are here: http://onsi.github.io/gomega/#gstruct-testing-complex-data-types

I think it does exactly what you need.

**Comment by williammartin** [comment]
I'm just having a think about whether you can nest a `gstruct` matcher

**Comment by haichuanyu** [comment]
Let's give a try

**Comment by haichuanyu** [comment]
yeah, it works. in case anyone reads this in the future, you want something like:

`Expect(myStructArray).To(ContainElement(MatchFields(IgnoreExtras, Fields{ "Id": 12345 }))`

It works, so feel free to resolve. Still I think the HaveKeyWithValue method would be helpful and elegant- although gstruct is more powerful it introduces an additional dependency and offers a lot of functionality that is not useful most of the time.

**Comment by nodo** [comment]
Thanks @haichuanyu! I am closing the issue for now. However, feel free to re-open if you have more feedback.

**Comment by SOF3** [comment]
How would this work with matchers in `Receive()`? For example

```go
type MyStruct struct {
    Value string
    other fields
}
var ch <-chan MyStruct

Eventually(ch, timeout).Should(Receive(
    ExpectField("Value").Should(Equal(123))
))
```

I don't think using the name is a good idea, but some way to expect a condition on a getter of a value would be great.

**Comment by thediveo** [comment]
You should be fine to use `HaveField` in those cases where you just need to check some field(s), and ignore the others, as a more lightweight alternative to `gstruct`. That would be `Receive(HaveField("Value", 123))` or `Receive(HaveField("Value", Equal(123))`.
