### ISSUE TITLE
Flaky `gbytes` test

### ISSUE THREAD

**Issue by nodo** [onsi/gomega#285]
Sometimes running the `gbytes` tests, this error occurs.

```
• Failure [0.015 seconds]
Buffer detecting regular expressions [It] should fast-forward the buffer upon detection 
/tmp/build/a94a8fe5/gopath/src/github.com/onsi/gomega/gbytes/buffer_test.go:150

  Saw:
      abcde
  Which matches the unexpected:
      abc
```

It would be great to investigate why it is happening and fix the issue.

**Comment by blgm** [comment]
In directory `go/src/github.com/onsi/gomega/gbytes` we ran `ginkgo -untilItFails`. We saw the flake after 85 attempts, 3 attempts and 10 attempts on different runs. This suggests that the chance of a flake is quite high, so it's worth further investigation.

**Comment by blgm** [comment]
Taking another look at this. It took `3744` attempts to make it fail this time.  From the description of the `Detect()` method:
> Detect takes a regular expression and returns a channel.
The channel will receive true the first time data matching the regular expression is written to the buffer.
The channel is subsequently closed and the buffer's read-cursor is fast-forwarded to just after the matching region.

It specifically says that the channel will receive `true` **before** the buffer's read-cursor is fast-forwarded to just after the matching region. The implementation is consistent with the description.

The test runs in a different goroutine and could fail if the test runs between the `Detect()` channel returning `true` and the read-cursor being fast-forwarded.

**Comment by blgm** [comment]
Other attempts have found this happen after 2916, 13006, and also not occurring after 16900 attempts. It's a rare test failure. Given that this is a bug found by developers of Gomega (and not users), and given it's hard to reproduce and verify, my suggestion is that we pause the effort to fix it until something else drives us to do so.

**Comment by nodo** [comment]
Thanks @blgm! Agree, I think we can close the issue and re-open it if it becomes a problem.
