### ISSUE TITLE
ExpectWithOffset should provide more stack information

### ISSUE THREAD

**Issue by fraenkel** [onsi/gomega#29]
Its nice to have the feature that allows us to report how high up the stack the problem originated.  Besides the fact that it may not work all that well given nested invocations, the stack currently presented doesn't show where the root cause was.  Would it be more useful to use the value to hint at how much of the stack should be displayed vs just displaying the "caller"?  That way you have context as to where it might have originated as well as what triggered the failure.

**Comment by tnine** [comment]
Sorry to resurrect a dead issue.  Is there a way to do this programmatically when constructing the suite?  We use `go test` rather than installing gingkgo in our CI/CD env, and this would be helpful to configure in our test suites as the default.
