### ISSUE TITLE
MatchJSON should support json.RawMessage

### ISSUE THREAD

**Issue by jtarchie** [onsi/gomega#290]
There is a type (`RawMessage`) in `json` package that is typed alias `[]byte`.
We use the type on a struct that is used for unmarshaling JSON.
When we tried to use `MatchJSON` that `RawMessage` field on a JSON string, we received the following error:

```
MatchJSONMatcher matcher requires a string, stringer, or []byte.  Got actual:
        	    <json.RawMessage | len:55, cap:64>: [{"clusters":[{"cluster":"pizza-boxes"}],"name":"AZ1"}]
```

It looks like the type casting of `actual` in `MatchJSON` tests for a `[]byte`, but not a typed aliased version of it.

**Comment by nodo** [comment]
Yes, it totally makes sense. Thanks for spotting that. I think we should add a type assertion for `json.RawMessage`. WDYT?
