### ISSUE TITLE
simplify failure messages

### ISSUE THREAD

**Issue by grosser** [onsi/gomega#294]
atm:
 - each matcher needs to define NegatedFailureMessage and FailureMessage
 - each matcher needs to copy-paste `format.Message(actual, -something-, matcher.CompareTo[0])`

ideally it would be:
matcher can define only `FormatFailureMessage` as something like
```go
func (matcher *FooMatcher) FormatFailureMessage(actual interface{}) (message string) {
  return fmt.Sprintf("to be %s", matcher.Comparator)
}
```
and NegatedFailureMessage+FailureMessage are taken care of automatically

something like:
```go
type FooMatcher struct {
  BaseMatcher
}
```

... I can make a PR if that sounds good

/cc @williammartin

**Comment by williammartin** [comment]
@grosser Thanks for the thoughts. We're not sure that this will satisfy 100% of message cases right now. For example, glancing through the codebase I can see complications around:

https://github.com/onsi/gomega/blob/master/matchers/equal_matcher.go#L30-L38
https://github.com/onsi/gomega/blob/master/matchers/and.go#L30-L37

and there may well be more. Also, it feels like we would need to support both interfaces going forward, at risk of breaking any matchers outside of Gomega. It would either be breaking, or result in two competing interfaces causing confusion.

Please feel free to reopen if you strongly disagree.

Thanks
