### ISSUE TITLE
failure messages are largely untested

### ISSUE THREAD

**Issue by grosser** [onsi/gomega#295]
```
go-testcov github.com/onsi/gomega/matchers
ok  	github.com/onsi/gomega/matchers	0.324s	coverage: 85.7% of statements
matchers/have_key_matcher.go new uncovered sections introduced (6 current vs 0 configured)
matchers/have_key_matcher.go:38.84,39.28
matchers/have_key_matcher.go:40.20,41.69
matchers/have_key_matcher.go:42.10,43.60
matchers/have_key_matcher.go:47.91,48.28
matchers/have_key_matcher.go:49.20,50.73
matchers/have_key_matcher.go:51.10,52.64
.... 100 more lines or so
```

... I can open a few PRs to improve things where it's straight forward if there is any desire to get good code coverage ?

**Comment by grosser** [comment]
did not look to closely, but definitely some of the failure messages

**Comment by williammartin** [comment]
@grosser Did you have a think about submitting PRs for this?

**Comment by grosser** [comment]
think about it: yes
have nothing else to work on: no :D

**Comment by blgm** [comment]
@grosser, this issue has had little movement for about a year now. I'm in agreement with you that it's unfortunate that more failure messages are not tested. We are happy to review any more PRs that improve coverage. From a pragmatic perspective, I'm not sure there's much value in keeping this issue open as it's not driven much work in the past year, and having lots of inactive issues just causes noise for people trying to find and report bugs. I'm planning to close this issue off soon, but wanted to give you a chance to object if you'd like to.

**Comment by grosser** [comment]
I wanted to come back to this but always found other things that are more pressing ... fine to close it 👍
