### ISSUE TITLE
Proposal: Allow pointers to MatchFields(), MatchAllFields()

### ISSUE THREAD

**Issue by williamhaley** [onsi/gomega#303]
One minor inconvenience I find with the gomega `MatchFields` and `MatchAllFields` matchers is that they do not support struct pointers. Only a struct literal value is acceptable.

```
if reflect.TypeOf(actual).Kind() != reflect.Struct {
    return false, fmt.Errorf("%v is type %T, expected struct", actual, actual)
}
```

Often, this is fine, but I find it problematic when trying to match against elements in a slice containing pointers to structs.

```
arr := []*SomeStruct{
  &SomeStruct{
    SomeField: "garbage",
  },
  &SomeStruct{
    SomeField: "Some value",
  },
}
Ω(arr).Should(ContainElement(Fields{
  "SomeField": Equals("Some value"),
}))
```

The above example won't work and will yield the following if trying to use `MatchFields` or `MatchAllFields`.

```
• Failure [0.001 seconds]
MyApp
/Users/will/dev/my_test.go:21
      ...
      &{[foo-2 bar-a] 49 0xc0002ed1d0 0 } is type *SomeCustomStruct, expected struct

      /Users/will/dev/my_test.go:21
```

That's unfortunate, since it either requires me to find and convert my struct ptr from `arr` and dereference it, or else convert the whole `arr` to dereferenced values. At my organization, we almost explicitly deal with pointers to structs rather than struct values, and we often want to compare values in slices in our tests.

I think if we add a check to de-reference pointers just before the struct check, we can handle both struct values and pointers interchangeably without the end user needing to care.

I tested this locally and found it works if I make my own copy of `matchFields()` that looks like this.

```
// If `actual` is a pointer, dereference it.
if reflect.TypeOf(actual).Kind() == reflect.Ptr {
	actual = reflect.Indirect(reflect.ValueOf(actual)).Interface()
}
// Ensure that the value of actual is a struct.
if reflect.TypeOf(actual).Kind() != reflect.Struct {
	return false, fmt.Errorf("%v is type %T, expected struct", actual, actual)
}
```

If that makes sense to you, I can open a PR.

**Comment by zonr** [comment]
How about using [`PointTo`](https://godoc.org/github.com/onsi/gomega/gstruct#PointTo)? Take your snippet as example:

```go
arr := []*SomeStruct{
  &SomeStruct{
    SomeField: "garbage",
  },
  &SomeStruct{
    SomeField: "Some value",
  },
}
Ω(arr).Should(ContainElement(PointTo(MatchAllFields(Fields{
  "SomeField": Equal("Some value"),
}))))
```

**Comment by williamhaley** [comment]
That works perfectly. I was not aware that `PointTo()` already existed. Thanks for pointing that out @zonr. This issue is moot since `PointTo()` already exists, so I'll close this out.
