### ISSUE TITLE
ghttp timeouts / connection reset errors

### ISSUE THREAD

**Issue by jontonsoup** [onsi/gomega#306]
Hi friends! 

Thanks for this awesome library. I'm looking for a way to force the ghttp server to return a weird behavior such as a timeout or a connection reset error. Is there a way to do this without mocking my http client? 

Thanks!

**Comment by jontonsoup** [comment]
@williammartin thanks for the response! So that will cover the client timeout case, but I'm not sure how to do a connection reset. I missed this option in the docs. 

The resets is this error: connection reset by peer. 


My guess is its something like this, but I haven't tested yet. 

```
	s := ghttp.NewServer()
	s.RouteToHandler("GET", "/foo", func(rs http.ResponseWriter, r *http.Request) {
		rs.WriteHeader(http.StatusResetContent)
		return
	})
```
Thanks!

**Comment by williammartin** [comment]
Cool, let me know how it goes and whether we can close this.

**Comment by williammartin** [comment]
I'm going to close this, but feel free to reopen if you need more help around this. Thanks for using Gomega!
