### ISSUE TITLE
What versions of Go should gomega support?

### ISSUE THREAD

**Issue by williammartin** [onsi/gomega#315]
PR #314 has been opened to clean up some method names going forward. It uses type aliasing which is only available in Go 1.9+. Currently our Travis tests run against 1.6+, so this PR fails.

The Go [support policy](https://golang.org/doc/devel/release.html#policy) is N-1 major releases, so Go 1.11 and Go 1.10 will receive security patches (. I'd suggest we aim to keep a similar policy, I don't want us to be hamstrung by supporting older versions.

@joefitzgerald for visibility.

**Comment by nodo** [comment]
Yes, totally up to it. If I remember correctly there are bits of code that explicitly handle older version of Go and we can clean them up.

**Comment by blgm** [comment]
Where we get a clear advantage from dropping older versions, I think it's worth doing.  People who are stuck on old versions of Go can always use older versions of Gomega (or Ginkgo).

Should we take a new major version when we drop support for a Go version?  It's arguably a breaking change, and it help to advertise it.

**Comment by williammartin** [comment]
I'm inclined to agree with @joefitzgerald here that a major version should not be required. I also agree with George that visibility of a major release telling you why you broke is useful. In this instance I think I'm going to lean towards a minor release but we can decide that at release time, I'm going to merge the PR in the meantime since we have agreement that we don't need to maintain compatability further back.

**Comment by williammartin** [comment]
Would someone like to create a PR to note our policy in docs? 

@nodo Do you remember what bits of code there are? I thought that might just be ginkgo.

**Comment by edwardstudy** [comment]
Hi, George @blgm. How could I install old version under travis.yaml? Thank you.
