### ISSUE TITLE
gofmt in Travis doesn't provide useful output

### ISSUE THREAD

**Issue by williammartin** [onsi/gomega#320]
The build for #317 is failing like:

```
$ make test
[ -z "`gofmt -s -w -l -e .`" ]
make: *** [test] Error 1
The command "make test" exited with 2.
```

The reason it is failing is because the `-s` flag for `gofmt` is finding a simplification:

```
→ gofmt -s -l .
gstruct/keys.go
```

Firstly, we should probably capture that you should use `gofmt` to simplify in the contributors guide and secondly, we should ensure that when the builds fail due to `gofmt` they provide some useful output.

**Comment by blgm** [comment]
Fixed by d732d5e3484371927eab92502b8f69d71cc1e416
