### ISSUE TITLE
Proposal: Provide matcher for matching wrapped errors

### ISSUE THREAD

**Issue by williammartin** [onsi/gomega#334]
With the new Go proposal to support wrapped errors (https://go.googlesource.com/proposal/+/master/design/29934-error-values.md), maybe we should have a matcher that can unwrap errors for example, given a function:

```
func wrapError(err error) error {
    return errors.Wrap(err, "extra details")
}
```

We could assert like:

```
err := wrapError("some error")
Expect(err).To(WrapError("some error"))
```

**Comment by blgm** [comment]
We decided to build this into the existing `MatchError()` matcher for now, as this is a general purpose matcher for errors. We could add additional matchers to make very specific assertions about error matching in the future.
