### ISSUE TITLE
put Expect() in defer will cause strange behaviour

### ISSUE THREAD

**Issue by magicsong** [onsi/gomega#342]
like following code:
```go
defer Expect(thisTestCase.StopRouter()).ShouldNot(HaveOccurred(), "Faild to stop container")
```

`thisTestCase.StopRouter()` will executed immediately . Does anyone know the machinery in this behaviour

**Comment by BooleanCat** [comment]
Go will evaluate the arguments immediately (I think) and only defer execution of the outer most function call.

Have you tried wrapping the entire expect line in a function?

**Comment by magicsong** [comment]
@BooleanCat Thank you. there is no problem if i wrapped it in a function.  I think you are right, after i searching, i found the following statements:
> Each time a "defer" statement executes, the function value and parameters to the call are evaluated as usual and saved anew but the actual function is not invoked. Instead, deferred functions are invoked immediately before the surrounding function returns, in the reverse order they were deferred. That is, if the surrounding function returns through an explicit return statement, deferred functions are executed after any result parameters are set by that return statement but before the function returns to its caller. If a deferred function value evaluates to nil, execution panics when the function is invoked, not when the "defer" statement is executed.
