### ISSUE TITLE
Lazy evaluate the `optionalDescription` parameter

### ISSUE THREAD

**Issue by neowulf** [onsi/gomega#351]
Thanks for the great library! We have been extensively using this library for our tests.

Would it be possible to not eagerly evaluate `errors.Cause(err).Error()` as part of the `optionalDescription` in the following statement:

	Expect(err).To(Not(HaveOccurred()), errors.Cause(err).Error())

This statement causes a panic when `err` is nil. But, when there's an error, it'd be useful to know the cause / stacktrace. The following would be a workaround but be nice to avoid it.

	errString := ""
	if err != nil {
		errString= errors.Cause(err).Error()
	}
	Expect(err).To(Not(HaveOccurred()), errString)

**Comment by blgm** [comment]
It's not possible for Gomega to change how Go works, and I think Go will evaluate all the arguments to `To()` before calling it (please do correct me if I'm wrong). However in #193 it has been suggested that the `optionalDescription` could be a function, which could be lazily evaluated.
