### ISSUE TITLE
ContainsElements matcher

### ISSUE THREAD

**Issue by ashanbrown** [onsi/gomega#361]
I was surprised not to find an existing matcher called `ContainsElements` that asserts that a set of elements are a subset of another, similar to `ConsistOf`.  Does such a matcher exist?  Since I couldn't find it, I defined the matcher below for my tests, but it would only work with slices and arrays and not maps:

```golang
// ContainElements returns whether a slice contains all the elements in another slice
func ContainElements(elements interface{}) types.GomegaMatcher {
	value := reflect.ValueOf(elements)
	ms := make([]types.GomegaMatcher, 0, value.Len())
	for i := 0; i < value.Len(); i++ {
		ms = append(ms, &matchers.ContainElementMatcher{
			Element: value.Index(i).Interface(),
		})
	}
	return &matchers.AndMatcher{
		Matchers: ms,
	}
}
```

Would you be open to adding a `ContainsElements` matcher functionally similar to the above but the more complete error reporting and support for maps as well?  Thanks.

**Comment by blgm** [comment]
@ashanbrown, I can't find such a matcher either. You would be welcome to submit a PR for this.

**Comment by ashanbrown** [comment]
Thank you @ansd and @blgm.  Great solution.  Sorry for not following up on this myself.
