### ISSUE TITLE
Formatting matcher output

### ISSUE THREAD

**Issue by onsi** [onsi/gomega#37]
Originally from onsi/ginkgo#73

This may already be implemented, I just haven't found it.

When I have an expectation like this:

```
Expect(something).ToNot(BeNil())
```

If it fails, it logs a deep inspection of `something`. I find that in many cases this leads to overwhelming output. For example, one of my structures includes a `time.Time`. This is (surprisingly) over 250 of output due to a massive DST lookup table that's included in its `loc` field. Some of my data structures include http or file handles that can generate thousands of lines of output (sometimes recursively, leading to hundreds of "too deep for me, man" messages).

I had assumed that I could implement Stringer or GoStringer to control the logging output, but Ginkgo doesn't seem to use these. Is there any way to get control over how complex structures are displayed?

**Comment by khaf** [comment]
Sorry to revive such a long dead thread, but I think keeping the conversation in one thread is useful for the future readers.
There is a use case that I think is not covered by the current custom depth and stringer workarounds:
I have an object in my code that if dumped, it will generate a ~190MB text file! In general, I'd like to see the usual output (actually, for structs and maps, I'd rather see only a diff and not the whole dump, but I digress)
For this specific object, I'd rather implement a `GomegaStringer` interface to format it. In this case, I don't want to touch the `format.MaxDepth` and `format.UseStringerRepresentation` globally; I'd just rather implement the additional `GomegaString()` function in a test file as a helper only for this object. Do you think this a viable feature request?

**Comment by onsi** [comment]
I like the idea of a `GomegaString` convention.  Would you be up for submitting a PR?

**Comment by khaf** [comment]
Absolutely.

**Comment by onsi** [comment]
Thanks!  If you could also update the docs on the gh-pages branch that would be great too.

**Comment by khaf** [comment]
https://github.com/onsi/gomega/pull/427
I will make a PR for documentation after the review of this PR.

**Comment by khaf** [comment]
Now that I think of it, maybe it wouldn't be a bad idea to trim a big object's dump if it is bigger than a certain size - say around 2K characters - since it probably will not be useful anyway the way it is.

**Comment by onsi** [comment]
Agreed - I was thinking along similar lines.  You up for adding a bit more to the PR (I'm currently heads down working on Ginkgo [v2](https://github.com/onsi/ginkgo/issues/711) and would appreciate the help making this a more pleasant user experience).

How about a new top-level global in `format` like `format.MaxLength` set to `4000` characters or something.  If a representation exceeds `MaxLength` we truncate at `MaxLength` then inject this:

```
the very very long object here that goes on forever and ever but then gets trunc....

Gomega truncated this representation as it exceeds `format.MaxLength`.  Consider having the object provide a custom `GomegaStringer` representation or adjust the parameters in Gomega's `format` package.  Learn more here: https://onsi.github.io/gomega/#adjusting-output
```

to the end of the representation.  (Unless the object has implemented `GomegaStringer` in which case we always emit the whole thing.

This way the user gets immediate helpful feedback in their test and they can go off and learn more.  Thoughts?

**Comment by khaf** [comment]
100% agreed, even for the message! (I already even had the message, though yours is better English than mine)
Will make the PR in a bit.

**Comment by onsi** [comment]
thanks so much!

**Comment by khaf** [comment]
PR updated. I went the lazy way in updating the code, trying to change as little as I could.
While a test framework is not performance critical, I believe the format package should use `string.Builder` in most places, or even better, use `io.Writer` and avoid allocating memory as much as it can.

**Comment by onsi** [comment]
thanks @khaf !

**Comment by onsi** [comment]
oh - if you're still up for updating the docs, please do!  otherwise let me know and i can take care of it later.

**Comment by khaf** [comment]
Here you go https://github.com/onsi/gomega/pull/429
Thank you for your help!
