### ISSUE TITLE
Differences between Assertion types - NotTo vs ToNot is unclear

### ISSUE THREAD

**Issue by harishsurf** [onsi/gomega#380]
I wanted to know if there is any difference b/w `NotTo` vs `ToNot` used in gomega assertions or is it just a convenience provided to add more meaning to BDD.

I found from the [source code](https://github.com/onsi/gomega/blob/master/gomega_dsl.go#L319) that `Should` vs `To` is just a convenience. I was wondering if it was the same for `NotTo` vs `ToNot`?

The documentation doesn't provide any information about these Assertion types. I felt it would be nice to have a note explaining their differences.
Thanks!

**Comment by williammartin** [comment]
Hi @harishsurf, 

There is no difference between `NotTo` and `ToNot`, they are just syntactic sugar. Would happily welcome a PR with some doc clarification!

**Comment by blgm** [comment]
Fixed by #383
