### ISSUE TITLE
[feature request] snapshot testing support

### ISSUE THREAD

**Issue by morlay** [onsi/gomega#393]
inspired by https://jestjs.io/docs/en/snapshot-testing

this feature will be useful to test function for string generator.

a quick example https://github.com/go-courier/snapshotmacther/blob/master/match_snapshot_test.go

**Comment by onsi** [comment]
so the idea is that this is a way to manage fixture data within the matcher library?  i could see that growing in scope over time (e.g. moving in [this direction](https://github.com/vcr/vcr)) and i'm a bit hesitant to add it straight into Gomega core without getting a sense for how widespread the usage and utility would be.  would be happy to link to a third party library if there is one/you build one, though!
