### ISSUE TITLE
Merge docs sources to master

### ISSUE THREAD

**Issue by YuviGold** [onsi/gomega#396]
Took me time to find the repository docs hidden in a dedicated `gh-pages` branch.
GitHub search engine doesn't look for sources inside branches different than `master` so it isn't possible to just search for specific documentation code.

It would be much simpler if the documentation would be in a `docs` directory on `master`.
@onsi

**Comment by blgm** [comment]
There would definitely be advantages to having everything in the same branch:
- discoverability (as mentioned above)
- consistency (going back in time it's clear which documentation relates to which release)
- fewer PRs (you can update docs and implementation at the same time)

**Comment by onsi** [comment]
this makes sense to me.  and it looks like i can configure github to populate github pages from a docs directory on master.  i’ll work on this in the coming weeks as i get ginkgo closer to v2z

**Comment by TheDiveO** [comment]
(this seems to be done?)

**Comment by onsi** [comment]
yes indeed!
