### ISSUE TITLE
How to match error with boolean function?

### ISSUE THREAD

**Issue by kaoet** [onsi/gomega#425]
I want to test whether my `err` is "not exist", I found [`os.IsNotExist()`](https://pkg.go.dev/os#IsNotExist) in the standard library. How can I use it in my tests? I'm wondering something like
```go
Expect(err).To(MatchError(os.IsNotExist))
```
But that doesn't work.

**Comment by blgm** [comment]
```go
Expect(err).NotTo(HaveOccurred())

```
Does this help?

**Comment by onsi** [comment]
or if you want to assert the exact error you can:

`Expect(err).To(MatchError(os.ErrNotExist))`

that's the actual error.  `os.IsNotExist()` is a function - if you wanted to use it you would:

`Expect(os.IsNotExist(err)).To(BeTrue())`

**Comment by kaoet** [comment]
@onsi Thanks for helping.
Actually, I over simplified my use case. I was just taking `os.IsNotExist()` as an example.

My original use case is that, I have a library, which returns library specific error and provides `IsXXXError()` functions just like `os.IsNotExist()`. But that library doesn't provide a convient way to construct an error of specific type like `os.ErrNotExist`.

What I want to test is wheter my error is `nil` or is some error matching `IsXXXError()`. I want to write something like:
```go
Expect(err).To(Or(BeNil(), MatchError(IsXXXError)))
```
As you can see, since I want to use it inside `Or()`, I must convert `IsXXXError` into a matcher.

I think those `IsXXXError()` functions, which have signature `func(error)bool` is a common pattern in Go. Can we support those functions as parameter of `MatchError()`?

Moreover, can we have a quick way to convert arbitrary `func(...)bool` to matchers rather than having to write an implementation of `GomegaMatcher` interface?

<hr>

My current workaround is to use an if statement like:
```go
if err := DoSomething(); err != nil {
  Expect(IsXXXError(err)).To(BeTrue())
}
```
But it's long and doesn't give me useful error message when it fails. Gomega just says "false is not true".

**Comment by onsi** [comment]
hey @kaoet I think your best bet here is to make one custom matcher that takes a `func(...) bool` as an argument and handles your use case.

Something like:  `BeNilOrSatisfy(f func(...) bool{})`.  You could then write tests like:

`Expect(err).To(BeNilOrSatisfy(os.IsNotExist))`

I imagine such a matcher would not be too hard to write - but let me know if you'd like some help with it.

**Comment by blgm** [comment]
A helper function is another approach:
```go
err := DoSomething()
checkError(err)
```

```go
func checkError(err error) {
  switch err.(type) {
    case nil, OtherAcceptableErrorType:
      return
    default:
      ExpectWithOffset(1, err).NotTo(HaveOccurred(), "extra message can be added here")
    }
  }
}
```

**Comment by blgm** [comment]
Hi @kaoet. Have the responses above been helpful?

**Comment by kaoet** [comment]
No, finally we implemented a `MatchErrorFn()` matcher in our own project, because it's so commonly used.

I'm always thinking [`MatchError()`](https://onsi.github.io/gomega/#matcherrorexpected-interface) function in Gomega should support pass in a `func (error) bool` function as parameter in addition to `string` and `error`.
