### ISSUE TITLE
`ConsistsOf` / `ContainElements` matchers fail on slice w/ struct with a function member

### ISSUE THREAD

**Issue by maiqueb** [onsi/gomega#445]
I am using a slice of structures which have a function member.

Using the `ConsistOf` (and also `ContainElements`) matcher fails.

The following snippet triggers the issue:

```golang
import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("ConsistOf", func() {
	Context("with a slice", func() {
		Context("where a struct member is a function", func() {
			type aStruct struct {
				a string
				b func()
			}
			It("crashes and burns", func() {
				f := func() {}
				a := aStruct{
					a: "aaa",
					b: f,
				}
				Expect([]aStruct{a}).Should(ConsistOf(a))
			})
		})
	})
...
})
```

With the following error:
```bash 
  Expected
      <[]matchers_test.aStruct | len:1, cap:1>: [
          {a: "aaa", b: 0x78d800},
      ]
  to consist of
      <[]matchers_test.aStruct | len:1, cap:1>: [
          {a: "aaa", b: 0x78d800},
      ]
  the missing elements were
      <[]matchers_test.aStruct | len:1, cap:1>: [
          {a: "aaa", b: 0x78d800},
      ]
  the extra elements were
      <[]matchers_test.aStruct | len:1, cap:1>: [
          {a: "aaa", b: 0x78d800},
      ]

```
Is this scenario supposed to work ? 

If I use the `Equal` matcher it works as expected.

**Comment by onsi** [comment]
Are you seeing `Equal` work?  This does not work for me:
```
    Describe("ConsistOf", func() {
		Context("with a slice", func() {
			Context("where a struct member is a function", func() {
				type aStruct struct {
					a string
					b func()
				}
				It("crashes and burns", func() {
					f := func() {}
					a := aStruct{
						a: "aaa",
						b: f,
					}
					Expect(a).Should(Equal(a))
				})
			})
		})
	})
```

Gomega is using go's `reflect.DeepEqual` to test for equality and the [docs](https://golang.org/pkg/reflect/#DeepEqual) say that "Func values are deeply equal if both are nil; otherwise they are not deeply equal."  `ConsistOf` and `ContainElements` simply build off of `reflect.DeepEqual` as well so they're both going to have the issue you're seeing.

This is one of several limitations with `DeepEqual` - I may tackle rolling my own `DeepEqual` for Gomega that handles edges like this better (e.g. why not at compare the pointer address for the function?)  But (a) I'm focused on Ginkgo V2 right now and (b) I'm hesitant to diverge from the official go definition of equality which will likely evolve with time.

**Comment by onsi** [comment]
One option is to use [gstruct](https://onsi.github.io/gomega/#gstruct-testing-complex-data-types) to only test the non-function fields of your struct.  It makes for a bit of a wordy assertion but you could wrap it in a custom matcher if you're doing this sort of thing a lot.

**Comment by maiqueb** [comment]
> Are you seeing `Equal` work? This does not work for me:

Sorry for misleading you, I confirm the example below doesn't work. 

> 
> ```
>     Describe("ConsistOf", func() {
> 		Context("with a slice", func() {
> 			Context("where a struct member is a function", func() {
> 				type aStruct struct {
> 					a string
> 					b func()
> 				}
> 				It("crashes and burns", func() {
> 					f := func() {}
> 					a := aStruct{
> 						a: "aaa",
> 						b: f,
> 					}
> 					Expect(a).Should(Equal(a))
> 				})
> 			})
> 		})
> 	})
> ```
> 
> Gomega is using go's `reflect.DeepEqual` to test for equality and the [docs](https://golang.org/pkg/reflect/#DeepEqual) say that "Func values are deeply equal if both are nil; otherwise they are not deeply equal." `ConsistOf` and `ContainElements` simply build off of `reflect.DeepEqual` as well so they're both going to have the issue you're seeing.
> 
> This is one of several limitations with `DeepEqual` - I may tackle rolling my own `DeepEqual` for Gomega that handles edges like this better (e.g. why not at compare the pointer address for the function?) But (a) I'm focused on Ginkgo V2 right now and (b) I'm hesitant to diverge from the official go definition of equality which will likely evolve with time.

OK, fair enough. I think sticking with golang's definition of equality is the right thing to do long term.

> One option is to use [gstruct](https://onsi.github.io/gomega/#gstruct-testing-complex-data-types) to only test the non-function fields of your struct. It makes for a bit of a wordy assertion but you could wrap it in a custom matcher if you're doing this sort of thing a lot.

I'll take a look, thanks. I'll close the issue.
