### ISSUE TITLE
a customized matcher to verify part fields' equality of a complex struct

### ISSUE THREAD

**Issue by JiaYongfei** [onsi/gomega#456]
In our ginkgo tests, we need to assert lots of complex structs to see if it has the expected fields and values. 

With the existing gomega matchers, one way to use is writing the fields' assertion one by one, like
```
Ω(obj).ShouldNot(BeNil())
Ω(obj.Age).Should(Equal(int32(3)))
Ω(obj.Body.Legs).Should(HaveLen(2))
Ω(obj.Body.Legs[0].Name).Should(Equal(LegRight))
```

another way is using the gstruct, like
```
Ω(obj).Should(MatchAllFields(gstruct.Fields{
				"Age": Equal(3),
				"Body":MatchFields(IgnoreExtras,Fields{
					"Legs":MatchElements(myIdentifier, IgnoreExtras, Elements{
						"0": MatchFields(IgnoreExtras, Fields{
							"Name": PointTo(Equal(LegRight)),
						}),
					}),
				}),
			}))
```
 
Both ways are a little bit complex to write in our test scenarios, so we created another customized gomega matcher [respect](https://github.com/JiaYongfei/respect) to verify part fields' equality of a complex struct. With it, the assertion looks like this
```
Ω(obj).Should(Respect(&Person{
				Age:   int32(3),
				Body: Body{
					Legs: []*Leg{
						{
							Name: &LegRight,
						},
					},
				},
			}))
```
To benefit the other users who has the similar test scenarios, can we add this to gomega [custom matchers wiki](https://github.com/onsi/gomega/wiki)?

**Comment by onsi** [comment]
Very cool :)

Thanks for sharing, I've updated the custom matchers wiki to let people know about `Respect`!
