### ISSUE TITLE
is nested Eventually supported

### ISSUE THREAD

**Issue by ydp** [onsi/gomega#458]
Hi,

Thanks for the awesome project!

I'm testing a kubernetes related feature, used gexec to wrap `kubectl exec` command, because this might be hang, I used eventually to wait for the output of the command (session.Wait() is the same as Eventually per this [comment](https://github.com/onsi/gomega/blob/master/gexec/session.go#L142)), furthermore, I need to identify the output of `kubectl exec`, there is another Eventually in the outside, it basically like this:

```

// time.Sleep(10*time.Second)

Eventually(func() bool {
        command := exec.Command("kubectl", "exec", "...")
        session, err := gexec.Start(command, GinkgoWriter, GinkgoWriter)
        Eventually(session, "5s").Should(gexec.Exit())
        return strings.Contains(string(session.Out.Contents()), "keyword")
  }, "30s", "1s").Should(Equal(true))
```

Is this supported? In my test, I need to add the `time.Sleep` to make things work, which makes me think that this kind of nested Eventually is not really supported.

Is there any doc/code I can learn about how the eventually is implemented underneath? Thank you very much!

**Comment by blgm** [comment]
Hi @ydp. Just to check on the intention - is it that:
1) the command `kubectl exec ...` should be run multiple times until the output matches `keyword`
2) run `kubectl exec ...` once and wait for the output `keyword`?

I'm not sure whether nested `Eventually()` works, but I've used `gexec` to do both of the above, and can probably find an example if that would be helpful.

**Comment by onsi** [comment]
hey @ydp - the pattern I've usually followed is to make a pair of assertions in series.  The first asserts that the external system under test is in a state that's ready for the test (e.g. all objects have been created).  The second asserts that the expected behavior is observed.  What you're doing, instead, is to keep testing for the expected behavior until it succeeds.  That's totally reasonable and something I've observed a lot in the k8s community.  It makes a ton of sense in the context of an eventually consistent system.

The next release of Gomega (1.15.0) will allow you to nest assertions under `Eventually`:

```go
Eventually(func(g Gomega) {
        command := exec.Command("kubectl", "exec", "...")
        session, err := gexec.Start(command, GinkgoWriter, GinkgoWriter)
        g.Eventually(session, "5s").Should(gexec.Exit()) //note we use the passed in Gomega.  This allows Eventually to intercept errors
        g.Expect(session).Should(gbytes.Say("keyword"))
        // no need for a return, the Eventually only succeeds if all the internal assertions succeed.
}, "30s", "1s").Should(Succeed())
```

I'm hoping to have it shipped sometime this week or next.

**Comment by ydp** [comment]
@blgm  I was using the first option. Thank you for the reply!

@onsi yes, your sample code is what I expected, many thanks for the great work! Look forward to the next release! A follow up question is how is the timeout works, in you code, if total timeout should be 30 * 5 seconds, right?

**Comment by onsi** [comment]
I just pushed out 1.15.0 with this change.  Please take a look!

**Comment by ydp** [comment]
Hi @onsi I upgraded to 1.15.0, but when I wrote code like you suggested:

```
Eventually(func(g Gomega) {
        command := exec.Command("kubectl", "exec", "pod_name", "--", "wget",  "-q0-", "--timeout=2", "url_address") // the wget timeout is 2 seconds
        session, _ := gexec.Start(command, nil, GinkgoWriter)
        g.Eventually(session, "5s", "1s").Should(gexec.Exit()) // 5 seconds should be enough to timeout, right??
        g.Expect(session).Should(gbytes.Say("keyword"))
}, "30s", "1s").Should(Succeed())
```

it always report below error:

```
  Timed out after 5.000s.
  Expected process to exit.  It did not.
```

Note what I'm testing kubernetes NetworkPolicy, so the test case is expected that `kubectl` to timeout, and output should be something like: 

```
Download timeout
```

**Comment by onsi** [comment]
hey @ydp i'm not sure the issue is Gomega here.  It looks like the process hasn't exited within the five second timeout.  Have you tried bumping the timeout to see when it does exit?

**Comment by blgm** [comment]
Hi. I see that the code is not capturing STDOUT. Would it be possible to change that (by replacing `nil` with `GinkgoWriter`) in case there's a message that would help us to work out what's going on? For instance, it might be waiting for user input... Sometimes commands behave differently when run by Gomega compared to running in a terminal.

I understand that when the `wget` timeout is set to 2s, then a timeout of 5s on the `Eventually()` makes sense. But for diagnostic purposes, it would be interesting to increase the timeout to see what's going on. For instance would it be possible to set it to something like 5 minutes? This would give you time to find the process in the `ps` output and see whether it's really taking more than 5 seconds. Or maybe `kubectl` is adding 4 seconds overhead, and a slightly higher timeout would fix things.

**Comment by onsi** [comment]
+1 to @blgm 's comments!

**Comment by ydp** [comment]
@onsi @blgm Follow your suggestions, found that I made a stupid mistake that concat some args before passing into Command, which makes the flag unknown to `kubectl`, after fixing it, everything works fine! Thank you so much!
