### ISSUE TITLE
Gomega v1.15.0 behaviour change of Expect() within Eventually()

### ISSUE THREAD

**Issue by blgm** [onsi/gomega#460]
From my perspective this is an "informational issue" that I'm raising because I saw a change in behaviour. I think it could be argued that the change in behaviour was a bug fix, and that my code was relying on a bug in Gomega that's now fixed.  As such, I don't need a fix. However I'm raising this in case anyone sees something similar and has a different perspective on whether it's a bug or a bug fix. My suggestion is that if no-one comments before the end of August 2021, then this should just be closed.

I had some code that was doing this:
```go
Eventually(func() {
  response, err := http.Head(fmt.Sprintf("http://localhost:%d", port))
  Expect(err).NotTo(HaveOccurred())
  return response.StatusCode == http.StatusOK
}, Should(BeTrue()))
```
With previous Gomega versions, if there was an error (`err!=nil`), the `Eventually()` would continue to poll until my server had started.

With Gomega v1.15.0, if there is an error, then the test fails immediately.

I'm of the opinion that the bug was in my code, and I've updated it to:
```go
Eventually(func() {
  response, err := http.Head(fmt.Sprintf("http://localhost:%d", port))
  return err == nil && response.StatusCode == http.StatusOK
}, Should(BeTrue()))
```
I'm aware that I could also fix it with an `Eventually(func(g Gomega) { ...`, but this seemed simpler.

**Comment by onsi** [comment]
> With previous Gomega versions, if there was an error (err!=nil), the Eventually() would continue to poll until my server had started.

Is this true?  In 1.14 this was true (briefly) - but in prior versions the `Expect` in the `Eventually` would call Ginkgo's `Fail` and so the test would be marked as failed.  No?

Another way to put it: 1.15 does not change the behavior of the code you've written relative to 1.13 and before.  It was only 1.14 that briefly introduced a change.

**Comment by blgm** [comment]
You're absolutely correct @onsi. The code only works with Gomega@v1.14.0 and not with Gomega@v1.13.0. It's funny how memory works: I was sure that was old code, but GitHub says I wrote it on 22nd July, which is after Gomega@v1.14.0 was released.
