### ISSUE TITLE
go get github.com/onsi/gomega/... produces error

### ISSUE THREAD

**Issue by janakiramanmesh7** [onsi/gomega#468]
src/github.com/onsi/gomega/gmeasure/cache.go:69:18: undefined: os.ReadDir

**Comment by blgm** [comment]
Hi @janakiramanmesh7 

The `os.ReadDir()` function was [added in Go 1.16](https://pkg.go.dev/os#ReadDir). Go 1.16 is the minimum supported version of Go.

We realise that for various reasons people may need to stay on older versions of Go. In this case, it's worth pinning to a specific version of Gomega that supported that version. This allows for the Gomega project to move forward, and you can update at a later stage. For instance, you could use the release `v1.16.0` as this does not have a usage of `os.ReadDir()`.

**Comment by stmcginnis** [comment]
As of December, we're now on go 1.17. Even go 1.16 was dropped as of https://github.com/onsi/gomega/pull/532. Looks like this can be closed?

**Comment by onsi** [comment]
imo I think it's ok to close this out.  I imagine google will bring folks to this thread and they can pin to an older version.  I don't _think_ they need to do a `replace` (?) - rather  `go get github.com/onsi/gomega@v1.16.0` should be enough?
