### ISSUE TITLE
Eventually(session).Should(gexec.Exit(0) hanging for ~45s after session ended before continuing

### ISSUE THREAD

**Issue by TheDiveO** [onsi/gomega#473]
I'm seeing some really strange behavior with running a bash script in a unit test and `Eventually(...).Should()` still blocking for around 40-50s after the script itself has terminated. I've checked that there are no waiting child processes in the script.

This is how I start the session and wait for it:

```go
session, err := gexec.Start(
	exec.Command("./test/cind/setup.sh"),
	GinkgoWriter,
	GinkgoWriter)
Expect(err).NotTo(HaveOccurred())
Eventually(session, "90s", "500ms").Should(gexec.Exit(0))
```

And this is the script:

```bash
#!/bin/bash
TESTDIR=$(dirname "$0")
. "${TESTDIR}/common.sh"

# Stop and get rid of any old running instance, as we want to start anew.
docker rm -f ${CNTR_NAME}

# Build the testing image, if not already cached.
docker build --build-arg "KINDBASE_IMAGE=${KINDBASE_IMAGE}" -t ${CIND_IMAGE} ${TESTDIR}

# Fire it up...
docker run -d -it --rm --name ${CNTR_NAME} --privileged ${CIND_IMAGE} || exit 1

# Now wait for the test container to have spun up and be ready...
exec 3< <(docker logs -f ${CNTR_NAME})
DOCKERLOGS_PID=$!
NEXTDOT=0
echo -n "waiting for test container"
while IFS= read -r <&3 LINE; do
    if echo "$LINE" | grep -q "SLEEPY READY"; then
        break
    fi
    ((NEXTDOT--))
    if (( ${NEXTDOT} <= 0 )); then
        echo -n "."
        NEXTDOT=${LINESPERDOT}
    fi
done
exec 3<&-
echo
if [[ $(docker inspect -f '{{.State.Running}}' "${CNTR_NAME}") == "true" ]]; then
    kill $DOCKERLOGS_PID
    echo "container in container spun up"
else
    echo "ERROR: failed to correctly start testing container"
    exit 1
fi
exit 0
```

I'm wondering if the session hangs in a final I/O copy but can't see how this could be happen? Any suggestions?

**Comment by onsi** [comment]
couple questions:

does it succeed after the 45s?

does `exec.Command(…).Run()` behave differently?

**Comment by TheDiveO** [comment]
- "_does it succeed after the 45s?_" Yes, it does. Nota bene: when just running `/bin/true` it immediately succeeds without "hesitation".
- "_does ... behave differently?_" Yes, time-wise it runs for the expect ~10s and then immediately proceeds.

**Comment by onsi** [comment]
ok thanks.  these sorts of things can be really finnicky to debug.  are you running in ginkgo v2 by any chance?  if so can you ^C when you think it’s stuck and attach the goroutine dump that ginkgo generates?

that might give us some clues.

under the hood gomega is just using exec.Cmd.Start and exec.Cmd.Wait.  it’s possible gexec is hanging waiting for a mutex in the gexec implementation to free up but the code is pretty simple and nothing is jumping out at me.  you can also try taking the GinkgoWriter out of the equation just in case that’s doing something weird somehow

**Comment by TheDiveO** [comment]
You got me thinking about debugging the test in VSCode: interestingly, `Session.monitorForExit()` sits in `s.Command.Wait()` for the whole time, so this is something happening already in Command. What I really don't understand that a plain `exec.Command("./test/cind/setup.sh").Run()` successfully terminates in the expected time, not hanging around for some more cups of coffee (is there a Gomega matcher for this yet?).

I remember once testing without `GinkgoWriter` to exclude it from the suspects list.

**Comment by TheDiveO** [comment]
It get's weirder than `Expect().ed`...

This one **works correctly**, that is, it immediately proceeds after script termination; this is just echoing everything unconditionally to stdout:

```go
By("starting an additional container engine in a container")
cmd := exec.Command("./test/cind/setup.sh")
cmd.Stdout = os.Stdout
cmd.Stderr = os.Stdout
cmd.Start()
cmd.Wait()
```

But now with `GinkgoWrite` it hangs around, having a nice cub of coffee, smokes some stuff, and only later proceeds, long after (seemingly) script termination...

```go
By("starting an additional container engine in a container")
cmd := exec.Command("./test/cind/setup.sh")
cmd.Stdout = GinkgoWriter
cmd.Stderr = GinkgoWriter
cmd.Start()
cmd.Wait()
```

**Comment by TheDiveO** [comment]
This [answer to "Bash Script hangs when run in go program"](https://stackoverflow.com/a/56384999) got me on the right track: for whatever reason, the background `docker logs` causes this hang, even when `kill -9`'ed, but the blocking can be avoided by sending that background command's stdin and stdout into the orcus:

`exec 3< <(docker logs -f ${CNTR_NAME} </dev/null 2>/dev/null )`

And now, unit testing immediately proceeds after the script has terminated and with using `GinkgoWriter`.

A **big thank you** for your ideas about how to debug this curious situation and sorry for the noise.

**Comment by onsi** [comment]
OMG @TheDiveO this made for some amazing and *hilarious* reading this morning.  Thank you for digging into it and finding the answer!  Over the years I've seen people bump into similar behavior and we've never been able to figure it out.  Thank you so much for persevering and figuring it out `Eventually()`.

Go get some coffee, you've earned it ;)

**Comment by TheDiveO** [comment]
`Eventually().To(HaveCoffee())`. An example of PDT ... pain-driven testing.
