### ISSUE TITLE
[RFC] new Value matcher?

### ISSUE THREAD

**Issue by TheDiveO** [onsi/gomega#484]
I would like to get feedback before venturing into this area: in several projects (not least [@thediveo/lxkns](https://github.com/thediveo/lxkns)) I want to express assertions regarding high-level objects in a also comparably highly cross-references information model.

The custom domain-specific matchers should be versatile to use and especially when used in different contexts, test spec writers shouldn't need to worry whether a `ContainElement(...)` will need a `PointTo` or not. Especially when combining lower abstraction matchers into higher abstraction matchers, using and not using `PointTo` becomes a distracting low-level and cumbersome aspect. This is even more painful as the Go compiler itself hides direct and indirect accesses in many places, so we only need to write `x.y` without caring whether `x` is a pointer to a value, or a value.

Would a `Value` matcher be useful as a generic Gomega matcher, where it resolves any `*v` to its `v`, while passing a `v` as is?

**Comment by onsi** [comment]
This makes sense to me.  I'm not sure that `Value` is the right name for the matcher - perhaps `ResolveValue`?

Also, how do you think should things behave if the pointer points to a pointer?  Does it keep resolving until it gets to a value?  Or does it stop after the first resolution?

**Comment by TheDiveO** [comment]
- pointers to pointers: very good question.
  1. I wonder, if there is a real-world use case for a pointer value pointing to just a pointer value of its own type, outside `unsafe` tricks? I don't think so.
  2. "deep pointers", such as `**string` -- I think I've even seen triple-star'd code in C, but this looked very suspicious. However, I can see places where a double star might come in, albeit that might be C-style "out" parameter passing shoe-horned into Go. Do you think that's a real use case? A repeated pointer resolving won't be a problem and could be limited.
- naming: you mirror my thinking 😀. However, I'm under the impression that `Expect(pv).To(ResolveValue(Equal(42)))` stutters more than `Expect(pv).To(Value(Equal(42)))`. A con for `Value` is a higher chance for conflicting with the dev's types when using the usual dot-import. Do you think `HaveValue` might be better, such as in `Expect(pv).To(HaveValue(Equal(42)))`?

**Comment by onsi** [comment]
re naming - `HaveValue` seems right to me.  `Expect(pv).to(HaveValue(Equal(42)))` conveys exactly what the user is intending to do.

re pointers to pointers: I totally agree that the use case doesn't seem real.  It just popped up as an edge case to consider.  If we go with `HaveValue` I could see a case being made for "keep resolving until you get down to an actual value."

**Comment by TheDiveO** [comment]
successfully done :)
