### ISSUE TITLE
MatchOneOf

### ISSUE THREAD

**Issue by karlkfi** [onsi/gomega#50]
Created a MatchOneOf "or matcher" for BOSH. I'd love to see something similar in Gomega.
https://github.com/cloudfoundry/bosh-agent/tree/master/matchers

`Expect(ip).To(MatchOneOf(Equal("a"), Equal("b")))`

I wanted to have a more englishy syntax, but `Expect(ip).To(Equal("a").Or(Equal("b")))` would require matchers to return an object instead of a boolean.

**Comment by karlkfi** [comment]
I just improved the impl in the agent:
- better output
- takes non-matchers as input (defaults to Equal if not a matcher)

```
Expect(ip).To(MatchOneOf("abc", 123, []string{"x", "y", "z"}, BeNumerically("<", 1)))
```

P.S. I wish format.formatType & format.formatValue were public.

**Comment by jim-slattery-rs** [comment]
FYI - Gomega has recently gained `SatisfyAny(...)` (aka `Or`), which looks equivalent to the proposed `MatchOneOf`: https://github.com/onsi/gomega/pull/108
Related docs: http://onsi.github.io/gomega/#composing-matchers

**Comment by karlkfi** [comment]
Awesome. thanks!
