### ISSUE TITLE
[RFC] "Expecting" ContainElement to return its findings

### ISSUE THREAD

**Issue by TheDiveO** [onsi/gomega#525]
In some of my projects I end up far too often with some slice (such as `[]*Container`) where I expect one particular element to be contained in the slice. In addition, I then need to check further with several, more complex, expectations about that particular container. As lumping all together into a single long-winded matcher "freight train" isn't neither desired nor easy to understand and maintain, I usually ended up in the past with:

```go
var cntrs []*Container = someFoo()
var container *Container
for _, c := range cntrs {
    if c.Name == "foo" && c.Type == "bar" {
        container = c
        break
    }
}
Expect(c).NotTo(BeNil())
// ...more Expect'ations
```

After the fifth time or so this really gets tiresome and error-prone, so I wondered why not to reuse all the beautiful Gomega matchers and have a `ContainElement`-like filter that accepts the usual match, iterates over its actual (as usual), but now _returns_ its findings, with me `Expect()ing` to get some finding(s) returned:

```go
var cntrs []*Container = someFoo()
var container *Container
Expect(cntrs).To(ReturnElement(
        And(HaveField("Name", "foo"), HaveField("Type", "bar")).
    In(&container))
// ...more Expect'ations
```

This returns the matching elements in `container` and expects exactly one find/match -- because `*Container` points to a scalar, not a slice. In contrast, if passing the address of a slice, at least one find/match would be expected.

The naming might need some improvement. :grin:

And I freely admit, that this is taking Gomega into new territory.

What do you think? If you're interested, I can make a PR to better discuss it. I've already a working implementation with unit tests, but would like to further discuss this crazy idea in order to improve it.

**Comment by onsi** [comment]
hey @TheDiveO sorry for the delay.  I've been heads down on a different project these days but I'm back now :)

> And I freely admit, that this is taking Gomega into new territory.

_Actually..._ not [quite](https://pkg.go.dev/github.com/onsi/gomega#Receive).

I'm a fan of the idea.  We could go with `ReturnElement(<matcher>).In(<pointer>)`  as you suggest but I think I'd sooner have the signature be `ReturnElement(<matcher>, <pointer>)` as I imagine it's an error (or at least, a typo) to not include the `.In()` part.

With that said, we could extend `ContainElement` to handle this use case.  Today `ContainElement` takes a single expected value that is either a value or a matcher.  We could, instead, extend tit to take optional additional parameters.  If the user provides a pointer as the second parameter then `ContainElement` will capture the first matching value and place it in the pointer (and fail if it's the wrong type, etc.).

> In contrast, if passing the address of a slice, at least one find/match would be expected.

I'm less certain about this - it sounds like I would need a nil-check after the expectation to see if an element was found or not.  Why not fail if no find/match was expected regardless of whether passed a scalar or slice (though perhaps I'm misunderstanding?)

Anywho, sorry for the delay.  This is a great idea :)

**Comment by TheDiveO** [comment]
Re the not found case, you're perfectly right and I also finally arrived at that conclusion some days ago. If an empty result could be expected, then it's much clearer to explicitly declare so using `Or(BeEmpty(), ContainElement(...))`. Otherwise, no findings are always a non-match.

**Comment by TheDiveO** [comment]
Done. Thank you very much for merging!
