### ISSUE TITLE
Feature: goroutine leak testing

### ISSUE THREAD

**Issue by thediveo** [onsi/gomega#536]
This moves further discussion on a new `gleak` experimental/beta package for goroutine leak detecting and matching from [Ginkgo issue 603](https://github.com/onsi/ginkgo/issues/603) to Gomega, as discussed. A corresponding PR will follow.

**Comment by thediveo** [comment]
So I found a goroutine leak in one of my modules ... in some of the _tests_. 👀

Turns out that pulling container images using the containerd client leaves a persistent HTTP connection and some goroutines associated with it in the background. Fixing it by passing my own `http.Client` and then `defer`-ing closing all that HTTP client's idle connections. Something new learnt.

**Comment by thediveo** [comment]
@onsi while hunting my leaks I noticed (not unexpectedly) some inconvenience in the leak reporting. I would like to hear your recommendations based on your experience. Originally, I run into two issues: 1. Gomega quickly truncating the overall matcher failure Object dump of the `Goroutines`s, because the backtraces quickly add up to the default 4k limit. 2. this usually truncates off also several of the goroutines which usually are important.

At the moment, [`FailureMessage`](https://github.com/thediveo/noleak/blob/f2953eca05b7f175d365d31cde55f278e747c1a1/have_leaked_matcher.go#L176) uses a hand-rolled message instead of Gomega's `format.Object`. [`listGoroutines`](https://github.com/thediveo/noleak/blob/f2953eca05b7f175d365d31cde55f278e747c1a1/have_leaked_matcher.go#L187) generates the Goroutine dump, but currently leaves out the backtrace. However, the backtraces are often crucial in understanding what really is going on, as the topmost function name and creator of the goroutine often don't suffice.

What would you suggest how to generate (format) the goroutines with backtraces? I would like to not have any truncation. Would leaving out the file names and line numbers good or bad? Any other ideas?

**Comment by onsi** [comment]
hey @thediveo - it's super cool to see some immediate benefits from using this in your existing test suites :)

I'm trying to figure out where the truncation is happening.  For both [async](https://github.com/onsi/gomega/blob/4fbb0dcc4c195c15e41018f34e322246d4360cd5/internal/async_assertion.go#L177-L184) and [synchronous](https://github.com/onsi/gomega/blob/4fbb0dcc4c195c15e41018f34e322246d4360cd5/internal/assertion.go#L93-L100) assertions Gomega basically called `FaliureMessage` on the matcher and passes it into the `FailHandler` (which, for Ginkgo, doesn't do any truncation).  And I don't see the `noleak` code using any of the helper methods in the [`format`](https://github.com/onsi/gomega/blob/master/format/format.go) package to generate the `FailureMessage` which is where truncation would happen.

IMO given the backtraces are essential and their output is usually fairly consumable without truncation I'd say it's ok to blow past the 4k limit by using custom formatting as you are doing and give the user all the information they need to suss out what's leaking and why.  The only other thought I have would be to "go off script" and rewrite the backtraces to have the minimal amount of information necessary (e.g. a single line per function call with the function name and then just the filename (no path) + line number) could be more compact at the risk of being "different" from what Go users are used to seeing.

If you're seeing truncation with your current approach let me know as that would be a bug somewhere (I think).

**Comment by thediveo** [comment]
Good to hear that you also consider not truncating backtraces and optionally condensed format!

I'm now avoiding `format.Message` and `format.Object` for this specific use case and instead do my own message generation in `HaveLeaked.FailureMessage`.

The backtrace gets condensed in almost the way you suggest, that is, single lines of function call and source location. At the moment, I dump the full filename with path, but allowing to shorten source information to just filename without path is a good idea and could be controlled by an exported variable; not least the format package has several output settings to tweak!
