### ISSUE TITLE
RFC: a "forgiving" HaveField matcher

### ISSUE THREAD

**Issue by thediveo** [onsi/gomega#548]
In the past months, Gomega's matcher design has ventured -- or slightly gone astray 😬 -- into reusing matchers not only in a "direct" strict context, but also as filters. For instance, `HaveField` has on purpose "rigid" semantics: the tester expects `HaveField` to fail if the specified field is missing, not to silently not match. This clearly is important to quickly point out any mistakes in tests. `HaveField` is to reason about field values, not about field existence.

However, things get into broader scope when appropriating matchers for filtering instead: sometimes, the expectations are as before, such as "this field must be present". In other cases, such as with the recent experiments in resource leak detection for goroutines and file descriptors, a missing field isn't a failure but not a match instead.

While it might be that `gstruct` might already support such cases, especially `HaveField` has pathed the way for a more lightweight approach. I would like to ask for feedback and ideas how we can introduce matcher forgiveness in a way that doesn't water down the existing purposedly rigid error behavior, yet allows for lee room without introducing too much potential for hidden test bugs.

1. my gut feeling is that extending the existing `HaveField` matcher args would be feature creep, if possible at all. Or wouldn't it?
2. similar, I'm not yet seeing how a generic `Forgiving()` matcher might help that simply swallows any matcher errors, mapping them to non-matches instead. It looks like running with scissors to me. Do we even have the need for forgiveness when using other matchers?
3. what would you expect `HaveOptionalField` to default to if the field is missing? Matching or non-matching? Would make `HaveOptionalField(ACTUAL, VALUE, DEFAULT)` be making things better or worse?
4. ...or tackling this from a completely different angle, as I'm stuck in a corner with my idea?

**Comment by onsi** [comment]
hey @thediveo - I think I'm struggling to get concrete with the application you have in mind for `HaveField` in particular.  Perhaps you could change tack and share an example problem you're trying to solve so I can better wrap my head around the question?

Absent that, I read this a few times and kept coming back to "is this solved with `SatisfyAny()`".  Like, `HaveOptionalField()` is really trying to model `SatisfyAny(HaveField("bloop", "blarp"), <Something Else>)`

**Comment by thediveo** [comment]
@onsi let my try to explain; one recent use case would be with the file descriptor leakage detection. Maybe in some situations, test writers want to filter out some fds by supplying their own matchers, preferable build using the existing matchers. Now in the case of fds, `FileDescriptor` is an interface implemented by different underlying struct types. Your matcher will now be called with a wide variety of `FileDescriptor` backing types:

```go
Expect(Filedescriptors).NotTo(HaveLeakedFds(goodfds, HaveField("PeerName", "1.2.3.4:56789")))
```

The problem now is that `HaveField` will be passed all kind of structs of various types, and most of them won't have a `PeerName` field, but only socket fds will have. `HaveField` will return an error which `HaveLeakedFds` will dutifully pass on, because we consider errors to be errors and not non-matches.

I've looked into `SatisfyAny` a.k.a. `Or` and it does immediately return an error whenever one of the matchers passed to it return an error. In my view, that's correct behavior. It just doesn't fit this slightly special case where I would have matchers that do not fail but instead don't matcher under specific circumstances, so that these matchers can be used as filters.

Do my explanations hopefully clear things slightly up or did I successfully manage to make it even muddier? 😀

**Comment by onsi** [comment]
ah thanks, I get it now.  Some ideas:

- If `HaveField` doesn't find the field in question we have it return a specific type of error (e.g. `FieldNotFoundError`) and downstream matchers like `HaveLeakedFds` could know to ignore that specific kind of error.  This is idea is... meh.
- Potentially better idea: we change the signature of `HaveField` from `HaveField(field string, expected interface{})` to `HaveField(field string, expected ...interface{})`.  Then, when invoked _without_ and `expected` `HaveField` simply returns true if the field exists on `actual` or false if it does not.  Then one could do things like:

```go
Expect(Filedescriptors).NotTo(HaveLeakedFds(goodfds, And(HaveField("PeerName"), HaveField("PeerName", "1.2.3.4:56789"))))
```

which is a bit stuttery but maybe that's ok?

**Comment by thediveo** [comment]
I have to admit that I'm rather very hesitant to extend `HaveField` semantics by turning the existing single `expected` arg into an optional one and this only by Go's slightly ugly way of using variadic args. Keeping with the `And` approach it finally occurred to me to check with the file matchers (because we already have used up `HaveField`): while slightly elaborate ("JRM" would probably approve of this slightly Victorian flavor of TDD DSL), we already test for file exitance using `BeAnExistingFile`. So what do you think about `BeAnExistingField`, as in:

```go
Expect(foobar).To(And(BeAnExistingField("Baz"), HaveField("Baz", "Barrrrr")))
```

Is this something in between...?

**Comment by onsi** [comment]
That makes sense to me!  Go for it!
