### ISSUE TITLE
BeEquivalentTo fails to convert float64 to float32 before doing comparison

### ISSUE THREAD

**Issue by OladapoAjala** [onsi/gomega#550]
```go

g := gomega.NewWithT(t)
g.Expect(float32(82.219075)).To(gomega.BeEquivalentTo(float64(82.219075)))

```

The code above fails with:

Expected  <float32>: 82.21907806396484 to be equivalent to  <float64>: 82.219075

**Comment by onsi** [comment]
hey there - the conversion is happening but you are running into rounding issues.  For numerical comparisons it's best to use `BeNumerically()`.

**Comment by OladapoAjala** [comment]
I see, thanks. I had tried BeNumerically() and still had the rounding issues. Is it possible gomega handles this internally?

**Comment by onsi** [comment]
Gomega doesn't handle this "automatically", no.  It wants you to be explicit.  You can use

`Expect(float32(82.219075)).To(BeNumerically("~", float64(82.219075), 1e-5))`

**Comment by OladapoAjala** [comment]
Hmm, thanks. I'd close this issue now since a solution has been provided.
