### ISSUE TITLE
pre-defined port to run ghttp server

### ISSUE THREAD

**Issue by AbdallaMourad** [onsi/gomega#557]
Hi, 

I am trying to create multiple servers from the ghttp package e.g: `ghttp.NewServer()`. I want to specify a single port for each server I create. 

Is this feature currently available, if not is it possible to be implemented?

Thank you

**Comment by onsi** [comment]
hey there - if you just need to learn which port was picked you can use `server.Addr()`

if you want to be able to specify a port then use [`ghttp.NewUnstartedServer`](https://pkg.go.dev/github.com/onsi/gomega/ghttp#NewUnstartedServer) then specify a custom listener on `server.HTTPTestServer`

**Comment by AbdallaMourad** [comment]
Hey @onsi, This worked, Thank you!
