### ISSUE TITLE
[Feature Request] `Eventually().Within()`

### ISSUE THREAD

**Issue by thediveo** [onsi/gomega#562]
I would like to test the waters first and getting feedback on `Eventually` and timeout+polling interval configuration before a potential PR.

Not least as I'm now doing goroutine leak checking on a regular basis using our new, experimental `gleak` package I often end up needing to slightly increase the timeout and polling durations compared to defaults, but only in the leak test context. So far, we have two forms to express timeout and polling durations, the original one as well as the much more and slightly overly expressive variant:

- `Eventually(foo, "2s", "250ms").Should(BeClosed())` ... _very_ terse.
- `Eventually(foo)).WithTimeout(2*time.Second).WithPolling(250*time.Millisecond).Should(BeClosed())`
 
Would you accept a potential third variant or is this going to be potentially dangerous feature creep?

- `Eventually(foo).Within(2*time.Second).Should(BeClosed())`
- `Eventually(foo).Within(2*time.Second, 250*time.Millisecond).Should(BeClosed())`

The signature would be `Within(timeout time.Duration, ...polling time.Duration)`. The timeout would be mandatory, the polling interval optional. What do you think?

Apropos: any intention to tag a new official Gomega release...?

**Comment by thediveo** [comment]
Maybe it would have been originally better to have used `Eventually().Within().Every()` instead of the `WithTimeout` and `WithPolling` ... _sigh_.

**Comment by onsi** [comment]
gah, sorry again for the delay @thediveo - our summer schedule is in full swing which means I have less time than usual for code!

I'm all good with aliases - especially since these things are nicely namespaced into the structs returned by `Eventually/Consistently`.

**Comment by onsi** [comment]
and I'll tag a new gomega release asap

**Comment by onsi** [comment]
I do think `ProbeEvery` is better than `Every`
