### ISSUE TITLE
error checking: accept Error() as alternative to String()

### ISSUE THREAD

**Issue by pohly** [onsi/gomega#642]
In Kubernetes, we (not often) check for specific errors:
```
              gomega.Expect(err).To(gomega.HaveOccurred())
              gomega.Expect(err.Error()).To(gomega.ContainSubstring(`Invalid value: "foo-"`))
              gomega.Expect(err.Error()).To(gomega.ContainSubstring(`Invalid value: "bar.."`))
              gomega.Expect(err.Error()).NotTo(gomega.ContainSubstring(`safe-and-unsafe`))
              gomega.Expect(err.Error()).NotTo(gomega.ContainSubstring("kernel.shmmax"))
```

I can currently write this as two assertions:
```
              gomega.Expect(err).To(gomega.HaveOccurred())
              gomega.Expect(err.Error()).gomega.ContainSubstring(`Invalid value: "foo-"`),
			gomega.ContainSubstring(`Invalid value: "bar.."`),
			gomega.Not(gomega.ContainSubstring(`safe-and-unsafe`)),
			gomega.Not(gomega.ContainSubstring("kernel.shmmax")),
	      ))
```

I would like to reduce this to one assertion:
```
		gomega.Expect(err).To(gomega.SatisfyAll(
			gomega.HaveOccurred(),
			gomega.ContainSubstring(`Invalid value: "foo-"`),
			gomega.ContainSubstring(`Invalid value: "bar.."`),
			gomega.Not(gomega.ContainSubstring(`safe-and-unsafe`)),
			gomega.Not(gomega.ContainSubstring("kernel.shmmax")),
		))
```

This currently fails:

```
  [FAILED] ContainSubstring matcher requires a string or stringer.  Got:
      <*errors.errorString | 0xc00153ebb0>: {
          s: "Invalid value: \"foo-\"",
      }
```

I think would be consistent with the gomega design to allow `error` as an alternative for a `fmt.Stringer` and to call `Error()` to obtain a string when given an `error`.

The advantages are:
- in case of a failure, the full error object gets dumped
- IMHO clearer code (one statement about `err` instead of many)

**Comment by onsi** [comment]
hey there - obviously I'm open to this but want to point out what currently exists first.  You _can_ do all this with:

```go
Expect(err).To(MatchError(SatisfyAll(
	ContainSubstring(`Invalid value: "foo-"`),
	ContainSubstring(`Invalid value: "bar.."`),
	Not(ContainSubstring(`safe-and-unsafe`)),
	Not(ContainSubstring("kernel.shmmax")),
))
```

(note you don't need the `HaveOccurred` as `MatchError` performs a `nil` check for you).

I could imagine expanding`MatchError` to take multiple matchers that it implicitly `And`s together with `SatisfyAll` - but nothing else does that right now so it would end up being the odd one out.  Also the output you get for a failure given a composite matcher like `SatisfyAll` might not be as helpful as we'd like - but I'd be happy to  invest effort fixing that.

**Comment by pohly** [comment]
That looks promising. I think it can satisfy all cases that I had in mind for this issue, so we can (almost) close it.

The output could be a bit better, though:
```
  err := fmt.Errorf("foo")

  [FAILED] Expected
      <*errors.errorString | 0xc001517520>: {s: "foo"}
  to match error
      <*matchers.AndMatcher | 0xc00401f7d0>: {
          Matchers: [
              <*matchers.ContainSubstringMatcher | 0xc00401f710>{
                  Substr: "Invalid value: \"foo-\"",
                  Args: nil,
              },
              <*matchers.ContainSubstringMatcher | 0xc00401f740>{
                  Substr: "Invalid value: \"bar..\"",
                  Args: nil,
              },
              <*matchers.NotMatcher | 0xc001517550>{
                  Matcher: <*matchers.ContainSubstringMatcher | 0xc00401f770>{
                      Substr: "safe-and-unsafe",
                      Args: nil,
                  },
              },
              <*matchers.NotMatcher | 0xc001517580>{
                  Matcher: <*matchers.ContainSubstringMatcher | 0xc00401f7a0>{
                      Substr: "kernel.shmmax",
                      Args: nil,
                  },
              },
          ],
          firstFailedMatcher: <*matchers.ContainSubstringMatcher | 0xc00401f710>{
              Substr: "Invalid value: \"foo-\"",
              Args: nil,
          },
      }
```

Dumping the error as struct makes sense because it may contain additional details. However, I would also expect to see the result of `Error()` because (depending on the type of error), the actual error string might not be in the struct at all.

**Comment by thediveo** [comment]
you can even avoid the "broken pavement" `_, _, _, err := foo()` boilerplate (in case you needed it before) using `Expect(foo()).Error().To(...)`

**Comment by onsi** [comment]
woof - yeah that failure message could use some work.  will need to think about it - one areA i've been bumping into the last couple of days is the general problem of consistent and useful reporting when a (hierarchy of)submatcher(s) is involved.

right now most composite matchers just print the `format.Object` of the submatcher(s) but we can surely do better.

i'm knee deep in another project right now but will add this to my todo list for when i free up.

**Comment by pohly** [comment]
It's not just the matchers: the `Expected <*errors.errorString | 0xc001517520>: {s: "foo"}` would also be more informative when it included the `Error()` result.

I'm thinking of this case:
```
package test

import (
	"testing"

	"github.com/onsi/gomega"
)

type myError struct{}

func (m myError) Error() string {
	return "some error"
}

func TestSomething(t *testing.T) {
	g := gomega.NewGomegaWithT(t)

	err := error(myError{})
	// g.Expect(err).ToNot(gomega.HaveOccurred())
	g.Expect(err).To(gomega.MatchError(gomega.ContainSubstring("foo")))
}
```

I found that `HaveOccurred` includes the `Error` output:

        Unexpected error:
            <test.myError>: {}
            some error
        occurred
        
`MatchError` does not:

        Expected
            <test.myError>: {}
        to match error
            <*matchers.ContainSubstringMatcher | 0xc0000c3620>: {Substr: "foo", Args: nil}

This seems to be solved as a special case in `HaveOccurred`. Would it perhaps be better to let `format.Object` always include the `Error` result when it encounters an object that implements `error`?

**Comment by onsi** [comment]
Yes that makes sense - doing it at the `format.Object` level in particular.

**Comment by onsi** [comment]
hey sorry for the delay - i havent worked on the submatchers yet but the error output seemed like a higher priority anyway.  it's now fixed on v1.27.3 - now anytime `format.Object` sees an `error` it will add on the `Error()` message.

**Comment by onsi** [comment]
hey good catch.  i've fixed this on master and rearranged things so `format.Object()` prints the `err.Error()` representation first and _then_ the struct.  please take a look and i'll cut a release if it looks better to you.

**Comment by pohly** [comment]
That looks better, please cut a release.

**Comment by onsi** [comment]
thanks for taking a look - 1.27.4 is out now with this change

**Comment by thediveo** [comment]
Looks like the godoc documentation for `MatchError` https://github.com/onsi/gomega/blob/5129b5cf7d54245b130b241a4ace8a0d12442ab1/matchers.go#LL90C4-L90C4 needs an update: it only mentions matching an error or a sting, but not using other matchers. Will work on this.

**Comment by onsi** [comment]
❤️ thank you!On Mar 24, 2023, at 1:28 PM, TheDiveO ***@***.***> wrote:﻿
Looks like the godoc documentation for MatchError https://github.com/onsi/gomega/blob/5129b5cf7d54245b130b241a4ace8a0d12442ab1/matchers.go#LL90C4-L90C4 needs an update: it only mentions matching an error or a sting, but not using other matchers. Will work on this.

**Comment by thediveo** [comment]
I understand this to be done both as the feature and as the documentation, so we can close it.
