### ISSUE TITLE
HaveExactElements() doesn't work properly inside ContainElement or collection matchers

### ISSUE THREAD

**Issue by eiiches** [onsi/gomega#647]
Hi,

I've encountered a weird behavior when using HaveExactElements matcher. See this example:

```go
actual := [][]bool{
	{true},
	{false},
}
g.Expect(actual).To(ContainElement( // this fails, even though it should pass
	HaveExactElements(Equal(false)),
))
```

I expect this assertion to pass, because `actual` contains an element `[]bool{false}` which matches `HaveExactElements(Equal(false))`. But the assertion fails instead.

I believe the culprit is that HaveExactElementsMatcher leaves some internal state once its Match() returns false, which never gets cleaned and causes subsequent calls to always return false. Fwiw, cleaning the state [at the beginning of the Match()](https://github.com/onsi/gomega/blob/dbd4cb504ac2e8b5cdbeb204e9c75447f56cc39a/matchers/have_exact_elements.go#L21-L22) fixed the issue for me.

```diff
 func (matcher *HaveExactElementsMatcher) Match(actual interface{}) (success bool, err error) {
+ 	matcher.missingIndex = 0
+ 	matcher.extraIndex = 0
+ 	matcher.mismatchFailures = nil
+ 
 	if isMap(actual) {
```

Version: 1.27.2

**Comment by onsi** [comment]
hey good catch.  would you be up for submitting a pull request?

**Comment by eiiches** [comment]
Sure!
