### ISSUE TITLE
Return diff(s) of 2 strings

### ISSUE THREAD

**Issue by truongsinh** [onsi/gomega#66]
Using one of diff libraries, gomega should return a diff of 2 strings, especially handy for comparing 2 lengthy strings.
- https://github.com/sergi/go-diff
- https://github.com/aryann/difflib

**Comment by robdimsdale** [comment]
@truongsinh if this is still something you're interested in, you may be interested to know there is a PR open for this at https://github.com/onsi/gomega/pull/109

**Comment by muhqu** [comment]
To whom it may concern, I created my own matcher to create colored unified and/or word diffs using the `git diff` tool. e.g. `worddiff.MatchJSON(..)`

See https://github.com/muhqu/gomega-additions

**Comment by onsi** [comment]
Closing this out in favor of the PR
