### ISSUE TITLE
docs: wrong example by using ContainsSubstring 

### ISSUE THREAD

**Issue by bassistdev** [onsi/gomega#672]
Hi, just a little `godoc` issue at https://pkg.go.dev/github.com/onsi/gomega@v1.27.7#MatchError

In the example it says:

```go
Expect(err).Should(MatchError("an error")) //asserts that err.Error() == "an error"
Expect(err).Should(MatchError(SomeError)) //asserts that err == SomeError (via reflect.DeepEqual)
Expect(err).Should(MatchError(ContainsSubstring("sprocket not found"))) // asserts that edrr.Error() contains substring "sprocket not found"
```

But the correct method to use is `ContainSubstring`.

I found another file to be updated, so here is the two files:

* [docs/index.md](https://github.com/onsi/gomega/blob/master/docs/index.md)
* [matchers.go](https://github.com/onsi/gomega/blob/master/matchers.go)

**Comment by onsi** [comment]
thanks - are you up for submitting a PR for this?

**Comment by bassistdev** [comment]
sure
