### ISSUE TITLE
HaveEach(): Doc Comments Contradictory

### ISSUE THREAD

**Issue by jgrieger** [onsi/gomega#703]
The following doc comment:
https://github.com/onsi/gomega/blob/375648c5a99d936849f1191dbe52474d819fb4b5/matchers.go#L384
does not fit to the implementation anymore:
https://github.com/onsi/gomega/blob/375648c5a99d936849f1191dbe52474d819fb4b5/matchers/have_each_matcher.go#L27

The new behavior war introduced with #524.

Please let me know if I shall update the doc comment.

**Comment by onsi** [comment]
yes please do, thanks!
