### ISSUE TITLE
A way to comapre two maps

### ISSUE THREAD

**Issue by keisuke713** [onsi/gomega#726]
Is there a matcher that check if two maps are equal?
What I wanna to do is comparison of two maps, and if they do not hold the exact same key value pair, then display difference like below

```
a := map[string]string{
    "key1": "value1",
    "key2": "value2",
}
b := map[string]string{
    "key1": "value1",
    "key2": "value22",
}

Expect(a).To(HogeMatcher(b))
=> expect "key2: value2" but got "key2: value22"
```

I think gomega seems not to have such matcher, which provides detailed difference between two maps.
Therefore, in my project, I gonna create custom matcher that suit my above need, but if any matcher, could you let me know about it.

Best Regard.

**Comment by onsi** [comment]
hey @keisuke713 you can use `BeComparableTo()` - this uses [go-cmp](https://pkg.go.dev/github.com/google/go-cmp/cmp) under the hood and will give you a useful diff:

```
  [FAILED] Expected object to be comparable, diff:   map[string]string{
    	"key1": "value1",
  - 	"key2": "value2",
  + 	"key2": "value22",
    }
```

**Comment by keisuke713** [comment]
@onsi 
It works as I expected!
thanks!
