### ISSUE TITLE
Does this make sens? Eventually(..., "1s", "2s", ctx).Should(...)

### ISSUE THREAD

**Issue by guettli** [onsi/gomega#751]
From the docs at: https://github.com/onsi/gomega/blob/master/gomega_dsl.go#L375C2-L375C46

> Eventually(..., "1s", "2s", ctx).Should(...)

I think this example makes no sense.

If the timeout is 1s, then there will never be polling.

**Comment by onsi** [comment]
durp.  thanks - the example is indeed confusing.  I've changed it to `"10s", "2s"`
