### ISSUE TITLE
Helper to create a RoundTripper for ghttp.Server

### ISSUE THREAD

**Issue by Smirl** [onsi/gomega#769]
# Summary

Currently we can use `server := ghttp.NewServer()` to create a test server, then use `server.URL()` or `server.Addr()` to point our clients to the test server.

In some situations code is not written in such a way where the URL can passed to a function, or perhaps paths should be conserved. It is common for libraries to be able to configure a `http.Client`, and therefore a `http.Transport`. The interface `RoundTripper` allows us to take a request, modify it in someway, and return the response/error

## Proposal

Add a new method to `ghttp.Server` which returns a `RoundTripper`. This can then be used to build http clients, or wrap existing transports (i.e. in `req`'s `WrapRoundTrip` [link](https://req.cool/docs/tutorial/middleware-for-client-and-transport/)).

Because we need to send a real request to our test server, we still require an actual transport. Therefore, the method takes a `RoundTripper`. If this is `nil` then we can use `http.DefaultTransport`.

For example:

```golang
func (s *Server) RoundTripper(rt http.RoundTripper) http.RoundTripper {
	if rt == nil {
		rt = http.DefaultTransport
	}
	return RoundTripperFunc(func(r *http.Request) (*http.Response, error) {
		r.URL.Scheme = "http"
		r.URL.Host = s.Addr()
		return rt.RoundTrip(r)
	})
}

```

Where the helper `RoundTripperFunc` is as such. Note there is an open issue to add this to `net/http` in https://github.com/golang/go/issues/38479.

```golang
type RoundTripperFunc func (*http.Request) (*http.Response, error)

func (fn RoundTripperFunc) RoundTrip(r *http.Request) (*http.Response, error) {
	return fn(r)
}
```

## Example usage

```golang
var _ = Describe("A Sprockets Client", func() {
	var server *ghttp.Server
	var client *SprocketClient
	BeforeEach(func() {
		server = ghttp.NewServer()
		httpClient := http.Client{Transport: server.RoundTripper(nil)}
		client = NewSprocketClient(httpClient, "skywalker", "tk427")
	})

	AfterEach(func() {
		server.Close()
	})
})
```

**Comment by onsi** [comment]
heyo this make sense to me.  are you up for submitting a PR that includes an update to the [long-form docs](https://onsi.github.io/gomega/#codeghttpcode-testing-http-clients)?  thanks!

**Comment by Smirl** [comment]
@onsi Thanks for the fast response. I have raised #770. Let me know what you think.
