### ISSUE TITLE
time behaviour

### ISSUE THREAD

**Issue by james-lawrence** [onsi/gomega#79]
Is it intentional that time objects use deep equal to determine if two times are equivalent instead of the Equal method on the object? I could see it working either way so more curious than anything.

```
    Expected
        <time.Time>: {sec: 0, nsec: 0, loc: nil}
    to equal
        <time.Time>: {
            sec: 0,
            nsec: 0,
            loc: {name: "UTC", zone: nil, tx: nil, cacheStart: 0, cacheEnd: 0, cacheZone: nil},
        }
```

**Comment by onsi** [comment]
Sorry for taking forever to write back!

The `Equal` matcher is generic and operates on *any* values.  It does this by deferring to Go's `DeepEqual`.  Unfortunately this is an all or nothing deal -- I either rely on `DeepEqual` *or* I reimplement `DeepEqual` and add my own rules.

I agree that `time.Time` is a pain -- this has to do with the fact that time and time zones really *are* a pain .  `DeepEqual` demands exact equality at the struct level - it doesn't know that it's comparing a time object and it doesn't honor `Equal`.

One could imagine a `MatchesTime` matcher but that won't help when you're comparing a slice of `time.Time`s or when you're comparing structs that have `time.Time` fields. :/

Sorry I don't have a better answer.  This does come up again and again -- but I very much *don't* want to have to fork DeepEqual and add these sorts of special cases to it.
