### ISSUE TITLE
EnforceDefaultTimeoutsWhenUsingContexts cannot be used from users

### ISSUE THREAD

**Issue by toshipp** [onsi/gomega#790]
`EnforceDefaultTimeoutsWhenUsingContexts` was added in https://github.com/onsi/gomega/commit/e4c4265bd405e86ae80d3a65610604294f30f77e, but it was implemented as an internal Gomega method, therefore, we cannot use it.

We should the method in the Gomega interface, and also define the global method.

**Comment by onsi** [comment]
woops!  my bad, thanks for catching that and fixing it!
