### ISSUE TITLE
it is timeout err, prompt invalid memory

### ISSUE THREAD

**Issue by nkuacac** [onsi/gomega#81]
>
171         var outBuffer bytes.Buffer             
172         oldWriter := ginkgo.GinkgoWriter       
173         ginkgo.GinkgoWriter = bufio.NewWriter(&outBuffer)
174         cfOutBuffer := EnvCf(env, args...).Wait(10 * time.Minute).Out
>

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x70d77d]

goroutine 394 [running]:
github.com/onsi/gomega/internal/asyncassertion.func·001(0x87d670, 0x9)
	/root/go/src/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:133 +0x4cd
github.com/onsi/gomega/internal/asyncassertion.(*AsyncAssertion).match(0xc20851f900, 0x7f69eb7e64d8, 0xc20832d120, 0xc20832d101, 0x0, 0x0, 0x0, 0xffffffffffffffff)
	/root/go/src/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:155 +0x440
github.com/onsi/gomega/internal/asyncassertion.(*AsyncAssertion).Should(0xc20851f900, 0x7f69eb7e64d8, 0xc20832d120, 0x0, 0x0, 0x0, 0xc20851f900)
	/root/go/src/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:47 +0x5f
github.com/onsi/gomega/gexec.(*Session).Wait(0xc208403a10, 0xc20815d838, 0x1, 0x1, 0x8)
	/root/go/src/github.com/onsi/gomega/gexec/session.go:140 +0xfa

**Comment by onsi** [comment]
I'm sorry but this isn't really enough to go on.

What are you trying to do?  Can you point me at some code? etc.. etc.. etc..

Also - why are you setting the GinkgoWriter??  The gexec session allows you to pass in an arbitrary writer, you should be injecting your custom writer in yourself instead of swapping out the GinkgoWriter.

**Comment by nkuacac** [comment]
Thanks @onsi  for reply.
The code of custom writer is from https://github.com/cloudfoundry-incubator/pat/blob/master/workloads/cf.go#L145-L157, This function will be excuted in multi goroutines.
From the call stack above, you can see it is timeout, 
https://github.com/onsi/gomega/blob/master/internal/asyncassertion/async_assertion.go#L155
but finally, it prompt "panic: runtime error: invalid memory address or nil pointer dereference"

**Comment by onsi** [comment]
Sorry for taking so long - my best guess is that you are calling `expectCfToSay` *before* registering a Fail handler with Gomega.  Please reopen if you're still having trouble and give me step-by-step instructions to download repos and reproduce.
