### ISSUE TITLE
Receive() matcher does not work with "non-blocking" channel send

### ISSUE THREAD

**Issue by artemave** [onsi/gomega#82]
Was that wrong to expect the following to work?

```
		It("works for non-blocking send", func() {
			channel := make(chan bool)

			go func() {
				time.Sleep(100 * time.Millisecond)

				// non-blocking send
				select {
				case channel <- true:
				default:
				}
			}()

			Eventually(channel).Should(Receive())
		})

**Comment by onsi** [comment]
Hi @artemave - your example is not expected to work but the reason is subtle.

The `Receive` matcher performs a *non-blocking* read on the channel.
`Eventually` periodically polls the `Receive` matcher.

It is very unlikely (in fact, impossible with GOMAXPROCS=1) for your non-blocking send to take place *at the same time* as the non-blocking read.

Instead you'll need to do something a bit more "traditional" like:

```go
        It("works for non-blocking send", func() {
            channel := make(chan bool)

            go func() {
                time.Sleep(100 * time.Millisecond)

                // non-blocking send
                select {
                case channel <- true:
                default:
                }
            }()
            
            select {
                case <-channel:
                case <-time.After(time.Second):
                     Fail("timed out waiting to read from channel")
            }
        })
```

**Comment by artemave** [comment]
Yep, that is what I ended up doing.

Perhaps it might be worth mentioning this subtlety in the documentation? Because it certainly _looked_ broken on the surface.

**Comment by onsi** [comment]
yes good point.  I'll work on that now.

**Comment by akashjain971** [comment]
This can be achieved as follows

`
It("works for non-blocking send", func() {
            channel := make(chan bool)

            go func() {
                time.Sleep(100 * time.Millisecond)

                // non-blocking send
                select {
                case channel <- true:
                default:
                }
            }()

            Eventually(func() bool { return <-channel }).Should(BeTrue())
        })
`
