### ISSUE TITLE
Numerically for slice

### ISSUE THREAD

**Issue by lazywei** [onsi/gomega#84]
Hi,

I'm wondering if there is any provided matcher that is same as `BeNumerically("~", ..` but takes slice, e.g. `[]float64` as input?
Also, I'm wondering if I'd like `BeNumerically("~",..` to use relative error instead of absolute error, should I create a PR, or should I write a custom matcher (i.e., don't send such PR)?

Thanks.

**Comment by onsi** [comment]
What would the matcher do when given a slice?

For relative error I'd suggest writing a custom matcher (or, even, writing a function that wrapped `BeNumerically` and did the math to take your relative error and turn it into an absolute error).

**Comment by lazywei** [comment]
> What would the matcher do when given a slice?

In fact, two slices. The matcher should compare approximately each element in two slices (if we are using `BeNumerically("~", ..`)



> For relative error I'd suggest writing a custom matcher (or, even, writing a function that wrapped BeNumerically and did the math to take your relative error and turn it into an absolute error).

Is it possible to share my custom matcher among several different packages?

**Comment by onsi** [comment]
I think rolling your own slice matcher would make sense -- I don't know if there's a need to put something like that in Gomega -- it seems pretty specific to your usecase.

> Is it possible to share my custom matcher among several different packages?

Yes absolutely - a Gomega matcher is just an interface - you can implement something that satisfies that interface in any package and then import that package for your test suite.

**Comment by lazywei** [comment]
Got it. I'll then make myself matcher then. Thanks :-)

**Comment by lazywei** [comment]
Actually, what I want is a comparison between two gonum's matrix: `*mat64.Dense`. Thanks to Gomega's flexible interface, I've built a customized matcher for `mat64`. In case anyone is interested, please refer to: https://github.com/lazywei/gomegamat64
Thanks.

**Comment by onsi** [comment]
Ooh - very nice :)
