### ISSUE TITLE
Have a way to Error without failure

### ISSUE THREAD

**Issue by abourget** [onsi/gomega#85]
Go's `t.Error()` logs an error, but continues the test, where `t.Fatal()` logs an error plus ends the test. This is to do many checks before erroring out, otherwise, you always need to fix the first tests before even knowing that the next assertions fail.

Would we have a slightly looser `Expect()` call ? `Check()` or something ?

**Comment by onsi** [comment]
One can hack together some of this behavior today with `InterceptGomegaFailures` - but having `Check` be a thing that can live on its own is going to be some work.

It comes down to the fact that the Fail handler that Gomega and Ginkgo share is a single function.  I could overload that function to support for `Expect` and `Check` semantics but ideally the Fail handler would actually be an interface with multiple methods on it (e.g. `FailNow` vs `Fail` or some such).

Unfortunately - that's a backward incompatible change to Ginkgo :/

I'll think on it some more...

**Comment by abourget** [comment]
Hitting this limitation again while developing in `agouti`.  How would one hack a `Check`-like function with `InterceptGomegaFailures` ?

**Comment by onsi** [comment]
Implementing `Check` is likely to be difficult without making some non-backward compatible changes to Ginkgo.  However if the primary pain here is during development then you could do something like this while you're debugging a test:

```
It("should show me all the failures", func() {
  failures := InterceptGomegaFailures(func() {
     Expect(...).To(...)
     Expect(...).To(...)
     Expect(...).To(...)
     Expect(...).To(...)
     //etc...
  })
  Expect(failures).To(BeEmpty())
})
```

If you see yourself doing this a lot you could even write a simple `Debug` function:

```
func Debug(body func()) func() {
     return func() {
         Expect(InterceptGomegaFailures(body)).To(BeEmpty())
     }
}
```

And then:
```
It("should show me all the failures", Debug(func() {
     Expect(...).To(...)
     Expect(...).To(...)
     Expect(...).To(...)
     Expect(...).To(...)
}))
```

I know it's not great but it should at least alleviate some of the development pain.  There hasn't been a lot of demand for `Check`: 
  - typically if a failure has occurred you can't rely on the subsequent state of your test and you'll want to abort anyway
  - if you stick to short `It`s then this naturally becomes less of an issue
Which is not to say you're not finding it annoying!! Only that it hasn't been a very pressing issue for most people.

**Comment by gabrielf** [comment]
I seem to get the propposed Check-behaviour by default and I don't even want it :)

Am I not using Gomega correctly?

I expect the following code to fail only once on the first `Expect`:

```go
package main_test

import (
	"testing"
	. "github.com/onsi/gomega"
)

func TestMain(t *testing.T) {
	RegisterTestingT(t)

	Expect("").ToNot(BeEmpty())
	Expect("").ToNot(BeEmpty())
}
```

But instead I get two errors, one for each `Expect`:

```
$ go test
--- FAIL: TestMain (0.00s)
	testing_t_support.go:22: 
		/Users/gabriel/go/src/github.com/gabrielf/testing-sandbox/main_test.go:11 (0x5bedb)
			TestMain: Expect("").ToNot(BeEmpty())
		/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:447 (0x5656f)
			tRunner: test.F(t)
		/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 (0x3b071)
			goexit: 
		Expected
		    <string>: 
		not to be empty
	testing_t_support.go:22: 
		/Users/gabriel/go/src/github.com/gabrielf/testing-sandbox/main_test.go:12 (0x5bff4)
			TestMain: Expect("").ToNot(BeEmpty())
		/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:447 (0x5656f)
			tRunner: test.F(t)
		/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 (0x3b071)
			goexit: 
		Expected
		    <string>: 
		not to be empty
FAIL
exit status 1
FAIL	github.com/gabrielf/testing-sandbox	0.004s
```

**Comment by jim-slattery-rs** [comment]
> I seem to get the propposed Check-behaviour by default and I don't even want it :)

@gabrielf: I think this is finally fixed: https://github.com/onsi/gomega/pull/215
