### ISSUE TITLE
Starting with --race option causes ginkgo to try installing something in GOROOT

### ISSUE THREAD

**Issue by bong0** [onsi/gomega#86]
When running `ginkgo --race` ginkgo quits unexpectedly with the following output:
```
Failed to compile my_module_name:

go install runtime: mkdir /usr/lib/golang/pkg/linux_amd64_race/: permission denied

Ginkgo ran 1 suite in 5.038912734s
Test Suite Failed
```
go env:
```
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/dev/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```
OS: Fedora 21, go 1.3

I cannot debug any further into this since ginkgo does not have a flag which enables outputting what it's actually trying to do. `go install runtime` is also pretty non-explanatory for me. I will not be able to run tests as root as you may expect ;)

**Comment by onsi** [comment]
Sorry for the delay in getting back to you.

`ginkgo --race` is simply calling `go test -c --race` under the hood then executing the resulting test binary.  You might try running `go test --race` on its own to confirm this is an issue in Ginkgo.  It's likely an issue in your Go environment -- in particular it looks like Go is trying to compile bits of the standard library with the race detector enabled and is failing to place them in the Goroot.

In any event this seems at least partially relevant:
https://github.com/golang/go/issues/5459

**Comment by bong0** [comment]
@onsi Thank you for that issue you referenced! No need to apologize because of the delay.
Running `go install -race std` as root fixes it. It's obviously not your fault that this fails.
 
I will open up a ticket at fedora, maybe they add a package for that case.

**Comment by Julio-Guerra** [comment]
Same problem on debian stretch with debian's golang package.
But I don't get why the `go test --race` works while `ginkgo --race`.
`go test --race` correctly installs in my user's `GOPATH` while `ginkgo -race` installs like if `GOPATH=$GOROOT`...

@onsi Any idea?

> GOARCH="amd64"
> GOBIN=""
> GOEXE=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/home/julio/farjump/lab"
> GORACE=""
> GOROOT="/usr/lib/go"
> GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
> GO15VENDOREXPERIMENT="1"
> CC="gcc"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
> CXX="g++"
> CGO_ENABLED="1"

**Comment by Julio-Guerra** [comment]
ping

**Comment by andyday** [comment]
I've got the same issue.

**Comment by alaska** [comment]
This resurgence may be related to https://github.com/golang/go/issues/19151 suggest coordinating new activity on https://github.com/onsi/ginkgo/issues/324
