### ISSUE TITLE
Convenience methods for writing to a process's stdin

### ISSUE THREAD

**Issue by vito** [onsi/gomega#87]

**Comment by robdimsdale** [comment]
@vito can you give an example of the sort of problem you are looking to solve, and how gomega can assist you here?

An example of how to write to a process's stdin can be found at https://github.com/pivotal-cf-experimental/pivnet-resource/blob/master/acceptance/acceptance_suite_test.go#L276-L286

**Comment by williammartin** [comment]
@vito I'm going to close this as part of housekeeping unless you come back that this is still an issue for you.
