### ISSUE TITLE
BeEquivalentTo should coerce nested data as well.

### ISSUE THREAD

**Issue by rkofman** [onsi/gomega#97]
Of course, opinions may vary, but after reading "`BeEquivalentTo` will successfully match equivalent values of different types", I expected the same for nested data as well.
```
type H map[string]interface{}
ACTUAL := map[string]interface{}{
	"foo": "asdf"
}
EXPECTED := H{
	"foo": "asdf"
}
Ω(ACTUAL).Should(BeEquivalentTo(EXPECTED)) // works like a charm!
```
```
type H map[string]interface{}
ACTUAL := map[string]interface{}{
	"foo": "bar": map[string]interface{}{
		"zed": "asdf"
	}
}
EXPECTED := H{
	"foo": "bar": H{
		"zed": "asdf"
	}
}
Ω(ACTUAL).Should(BeEquivalentTo(EXPECTED)) // fails :(
```

Thoughts?

**Comment by onsi** [comment]
I agree but it would entail re-implementing `DeepEqual` (very carefully!) to be type-agnostic in this way :/

I'm open to that but am unlikely to have the time to do it.......  PR? ;p

**Comment by robdimsdale** [comment]
@rkofman as it doesn't look like a PR is forthcoming, I'm going to close this issue. Please feel free to open a new issue if you'd like to discuss a PR or if you have further questions

**Comment by rkofman** [comment]
Yeah, I dug in a bit and it turned out to be more difficult than I initially realized, and then I got distracted with other projects that don't require Go. So next time I'm in a Go mood, I'll take another look -- but in the meanwhile don't count on a PR from me :(

Cheers, and thank you for building/maintaining this great project: it is very useful :)
