### ISSUE TITLE
testing/quick testing

### ISSUE THREAD

**Issue by rnapier** [onsi/gomega#99]
Does Gomega have any way to generate tests similar to `testing/quick` (a la QuickCheck)? The idea is to test that a wide variety of random values work correctly.

**Comment by onsi** [comment]
woops! this totally slipped through the cracks.

I haven't used `testing/quick` very much but using it within Gomega would be trivial:

`Expect(Check(f, config)).To(Succeed())`

One could get fancy and write a custom matcher that uses `testing/quick` under the hood.  e.g.

`Expect(f).To(PassQuickCheck(config))`
`Expect(f).To(QuickCheckEqual(g, config))`

But the value of that sort of thing is probably minimal.

**Comment by onsi** [comment]
whoops wrong button
